<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hammer5Tools.Core\Hammer5Tools.Core.csproj" />
    <ProjectReference Include="../../third_party/CS2WorkshopManager/GUI/GUI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <EmbeddedResource Include="Features/SmartProps/SmartPropPresentation.json" />
    <EmbeddedResource Include="Assets/SmartProps/model_sm.png" LogicalName="Hierarchy.model" />
    <EmbeddedResource Include="Assets/SmartProps/vsmart_sm.png" LogicalName="Hierarchy.smartprop" />
    <EmbeddedResource Include="Assets/SmartProps/generic_sm.png" LogicalName="Hierarchy.generic" />
    <EmbeddedResource Include="Assets/SmartProps/animation_group_sm.png" LogicalName="Hierarchy.group" />
    <EmbeddedResource Include="Assets/SmartProps/model.vert" LogicalName="Shaders.model.vert" />
    <EmbeddedResource Include="Assets/SmartProps/model.frag" LogicalName="Shaders.model.frag" />
    <EmbeddedResource Include="Assets/SmartProps/grid.vert" LogicalName="Shaders.grid.vert" />
    <EmbeddedResource Include="Assets/SmartProps/grid.frag" LogicalName="Shaders.grid.frag" />
    <None Update="Features/SmartProps/Example.vsmart" Link="Example.vsmart" CopyToOutputDirectory="PreserveNewest" />
    <InternalsVisibleTo Include="Hammer5Tools.SmartProp.Tests" />
    <InternalsVisibleTo Include="Hammer5Tools.App.Tests" />

  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Dock.Avalonia" />
    <PackageReference Include="Dock.Avalonia.Themes.Fluent" />
    <PackageReference Include="Dock.Model.Mvvm" />
    <PackageReference Include="Dock.Serializer.SystemTextJson" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
  </ItemGroup>

</Project>
