"""Stable Python adapters for Hammer5Tools.Core public APIs."""

from core.bridge.core import (
    CoreBridge,
    CoreBridgeError,
    CoreStatus,
    SmartPropEvaluation,
    SmartPropModel,
    SnapshotDocument,
    SnapshotStream,
    UnrealMapWriteResult,
    VmapRewriteResult,
    ValveMapDocument,
    ValveMapEntity,
    ValveMapNode,
    ValveMapSceneDocument,
    ValveMapSceneMesh,
    ValveMapScenePlacement,
    ValveMapSceneSubMesh,
    VpkIndex,
)

__all__ = [
    "CoreBridge",
    "CoreBridgeError",
    "CoreStatus",
    "SmartPropEvaluation",
    "SmartPropModel",
    "SnapshotDocument",
    "SnapshotStream",
    "UnrealMapWriteResult",
    "VmapRewriteResult",
    "ValveMapDocument",
    "ValveMapEntity",
    "ValveMapNode",
    "ValveMapSceneDocument",
    "ValveMapSceneMesh",
    "ValveMapScenePlacement",
    "ValveMapSceneSubMesh",
    "VpkIndex",
]
