import time
from datetime import datetime, timezone
import os
import zipfile
import subprocess
import argparse
from typing import List, Set
from tabulate import tabulate
from src.common import app_version
import re
import sys
cur_dir = os.path.abspath(os.path.dirname(__file__))

external = f"--add-data={os.path.join(cur_dir, 'src', 'external')};src\\external"
print(f"External path: {external}")

# Path to your .NET DLLs
dotnet_dlls = [
    ("Datamodel.NET.dll", "src\\external"),
    ("ValveKeyValue.dll", "src\\external"),
    ("ValvePak.dll", "src\\external"),
    ("ValveResourceFormat.dll", "src\\external"),
    ("ZstdSharp.dll", "src\\external"),
    ("K4os.Compression.LZ4.dll", "src\\external"),
    ("SharpGLTF.Toolkit.dll", "src\\external"),
    ("SharpZstd.Interop.dll", "src\\external"),
    ("SkiaSharp.dll", "src\\external"),
    ("System.IO.Hashing.dll", "src\\external"),
    ("TinyBCSharp.dll", "src\\external"),
    ("TinyEXR.NET.dll", "src\\external")
]


# Path to your .NET DLLs


def print_elapsed_time(stage_name: str, start_time: float) -> None:
    """Prints the elapsed time for a given stage."""
    elapsed_time = time.time() - start_time
    print(f"{stage_name} took {elapsed_time:.2f} seconds")


def kill_process(process_name: str) -> None:
    """Kills a process by its name."""
    subprocess.run(
        ["taskkill", "/F", "/IM", process_name],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL
    )


def find_pycparser_tables():
    """
    Return (lextab_path, yacctab_path) if the pre-generated pycparser parser
    tables exist, or None if they are absent (pycparser >= 3.0 generates them
    lazily at runtime, so absence is normal).

    Search order:
      1. Local .venv / venv
      2. pycparser's own package directory (global installs, CI)
      3. Current working directory (generated by _generate_pycparser_tables)
    """
    try:
        import pycparser as _pycparser
        pycparser_pkg_dir = os.path.dirname(_pycparser.__file__)
    except ImportError:
        pycparser_pkg_dir = None

    candidates = [
        os.path.join(cur_dir, '.venv', 'Lib', 'site-packages', 'pycparser'),
        os.path.join(cur_dir, 'venv', 'Lib', 'site-packages', 'pycparser'),
    ]
    if pycparser_pkg_dir:
        candidates.append(pycparser_pkg_dir)
    candidates.append(cur_dir)  # fallback: generated into cwd

    for base in candidates:
        lextab = os.path.join(base, 'lextab.py')
        yacctab = os.path.join(base, 'yacctab.py')
        if os.path.isfile(lextab) and os.path.isfile(yacctab):
            return lextab, yacctab
    return None


def _generate_pycparser_tables():
    """
    Force pycparser to generate lextab.py and yacctab.py by instantiating
    its C parser with outputdir set to cur_dir so the files land somewhere
    predictable regardless of whether the package dir is writable.
    """
    try:
        try:
            import pycparser.ply.lex as lex
            import pycparser.ply.yacc as yacc
        except ImportError:
            import ply.lex as lex
            import ply.yacc as yacc
        # Monkey-patch outputdir so tables land in cur_dir
        _orig_lex = lex.lex
        _orig_yacc = yacc.yacc

        def _lex(*a, **kw):
            kw.setdefault('outputdir', cur_dir)
            return _orig_lex(*a, **kw)

        def _yacc(*a, **kw):
            kw.setdefault('outputdir', cur_dir)
            return _orig_yacc(*a, **kw)

        lex.lex = _lex
        yacc.yacc = _yacc
        try:
            from pycparser import c_parser
            c_parser.CParser()
            print("pycparser tables generated.")
        finally:
            lex.lex = _orig_lex
            yacc.yacc = _orig_yacc
    except Exception as e:
        print(f"Warning: could not pre-generate pycparser tables: {e}")



def build_cpp(project: str, src_dir: str, output_name: str) -> None:
    """Builds a C++ project using CMake."""
    build_dir = os.path.join(cur_dir, f"build_cpp_{project}")
    os.makedirs(build_dir, exist_ok=True)
    try:
        # Let CMake choose the best generator for the system
        subprocess.run(["cmake", "-S", src_dir, "-B", build_dir,
                        "-DCMAKE_BUILD_TYPE=Release"], check=True)
        subprocess.run(["cmake", "--build", build_dir, "--config", "Release"], check=True)
        
        # Copy exe to hammer5tools/
        # CMake might put the exe in build_dir or build_dir/Release (for MSVC)
        src_exe = os.path.join(build_dir, f"{output_name}.exe")
        if not os.path.exists(src_exe):
            src_exe = os.path.join(build_dir, "Release", f"{output_name}.exe")
            
        if not os.path.exists(src_exe):
            raise FileNotFoundError(f"Could not find built executable at {src_exe}")

        dst_exe = os.path.join(cur_dir, "Hammer5Tools", f"{output_name}.exe")


        os.makedirs(os.path.dirname(dst_exe), exist_ok=True)
        import shutil
        shutil.copy2(src_exe, dst_exe)
        print(f"Successfully built and copied {output_name}.exe")
    except subprocess.CalledProcessError as e:
        print(f"Error building C++ project {project}: {e}")
        raise


def build_app_pyinstaller(fast=False) -> None:
    """Builds the Python application using PyInstaller."""
    # Try to locate pre-generated pycparser tables; generate them if absent.
    tables = find_pycparser_tables()
    if tables is None:
        _generate_pycparser_tables()
        tables = find_pycparser_tables()

    pyinstaller_cmd = [
        sys.executable, '-m', 'PyInstaller',
        '--name=Hammer5Tools',
        '--contents-directory=app',
        '--noupx',
        '--distpath=out_hammer5tools',

        '--hidden-import=vpk',
        '--collect-all=velopack',

        '--noconfirm',

        '--onedir',
        '--windowed',

        '--paths=.',
        '--hidden-import=resources_rc',
        '--hidden-import=widgets',
        '--collect-all=src',
        '--collect-all=keyvalues3',
        '--collect-submodules=pycparser',
        '--hidden-import=PySide6.QtNetwork',
        '--hidden-import=PySide6.QtMultimedia',
        '--hidden-import=PySide6.QtMultimediaWidgets',
        '--hidden-import=cffi',
        '--collect-submodules=cffi',
        '--hidden-import=clr_loader',
        '--collect-submodules=clr_loader',
        '--optimize=0',
        '--icon=src/appicon.ico',
        '--add-data=src/appicon.ico;.',
        '--add-data=src/images;images/',
        '--add-data=src/styles;styles/',
        '--add-data=Hammer5Tools;defaults/',
        '--exclude-module=PyQt5',
        '--exclude-module=numba',
        '--exclude-module=scipy',
        '--exclude-module=pandas',
        '--exclude-module=tabulate',
        external,
        *[f'--add-binary=src{os.sep}external{os.sep}{dll};external{os.sep}{dll}' for dll, _ in dotnet_dlls],
        'src/main.py'
    ]

    if tables:
        lextab_path, yacctab_path = tables
        pyinstaller_cmd += [
            f'--add-data={lextab_path};pycparser',
            f'--add-data={yacctab_path};pycparser',
        ]
    
    subprocess.run(pyinstaller_cmd, check=True)


def build_hammer5_tools(fast=False, channel='stable') -> None:
    # Phase 0: Clean up the Hammer5Tools template folder to avoid recursive bundling


    # (We clean internal files but keep the source folder itself)
    template_dir = os.path.join(cur_dir, 'Hammer5Tools')
    if os.path.exists(template_dir):
        import shutil
        for item in ['app', 'Hammer5Tools.exe', 'Hammer5ToolsUpdater.exe']:

            path = os.path.join(template_dir, item)
            if os.path.exists(path):
                if os.path.isdir(path):
                    shutil.rmtree(path)
                else:
                    os.remove(path)
        print(f"Cleaned up template directory: {template_dir}")


    build_app_pyinstaller(fast=fast)

    # Final distribution folder
    bundle_root = os.path.join(cur_dir, 'Hammer5Tools')
    # Safe cleanup: only remove build artifacts, keep data folders
    for item in ['app', 'Hammer5Tools.exe', 'fileedit.exe', '_internal', 'Hammer5Tools']:
        path = os.path.join(bundle_root, item)
        if os.path.exists(path):
            if os.path.isdir(path): shutil.rmtree(path)
            else: os.remove(path)
    if not os.path.exists(bundle_root):
        os.makedirs(bundle_root)



    # Flatten the PyInstaller output: move contents from out_hammer5tools/Hammer5Tools/ up to Hammer5Tools/
    pyi_output = os.path.join(cur_dir, 'out_hammer5tools', 'Hammer5Tools')
    if os.path.exists(pyi_output):
        import shutil
        for item in os.listdir(pyi_output):
            src = os.path.join(pyi_output, item)
            dst = os.path.join(bundle_root, item)
            # Remove old versions if they exist
            if os.path.exists(dst):
                if os.path.isdir(dst): shutil.rmtree(dst)
                else: os.remove(dst)
            shutil.move(src, dst)
        shutil.rmtree(os.path.join(cur_dir, 'out_hammer5tools'))

    # Ensure data folders are present in bundle_root (they should be if it's the source folder)
    template_dir = os.path.join(cur_dir, 'Hammer5Tools')
    data_folders = ['Hotkeys', 'Presets', 'SmartPropEditor', 'SoundEventEditor']
    for folder in data_folders:
        src = os.path.join(template_dir, folder)
        dst = os.path.join(bundle_root, folder)
        if os.path.exists(src) and src != dst:
            if os.path.exists(dst): shutil.rmtree(dst)
            shutil.copytree(src, dst)
            print(f"Copied data folder {folder} to bundle root")
        elif not os.path.exists(src):
            print(f"Warning: data folder {folder} missing from template")





def archive_files(
    folder_path: str,
    output_path: str,
    excluded_files: Set[str],
    excluded_paths: List[str]
) -> None:
    """Archives files from a folder into a zip file with maximum compression, excluding specified files and paths."""

    def should_exclude(file_name: str, file_path: str) -> bool:
        if file_name in excluded_files:
            return True
        for excluded_path in excluded_paths:
            if excluded_path in os.path.normpath(file_path):
                return True
        return False

    with zipfile.ZipFile(output_path, 'w', compression=zipfile.ZIP_DEFLATED, compresslevel=6) as archive:
        for root, _, files in os.walk(folder_path):
            for file in files:
                file_path = os.path.join(root, file)
                rel_path = os.path.relpath(file_path, folder_path)
                if should_exclude(file, rel_path):
                    continue
                try:
                    archive.write(file_path, rel_path)
                except OSError as e:
                    print(f"Warning: Could not add file {file_path}: {e}")

    original_size = sum(
        os.path.getsize(os.path.join(root, file))
        for root, _, files in os.walk(folder_path)
        for file in files
        if not should_exclude(file, os.path.join(root, file))
    )
    compressed_size = os.path.getsize(output_path)
    compression_ratio = (1 - compressed_size / original_size) * 100 if original_size > 0 else 0

    print(f"Archived files to {output_path}")
    print(f"Original size: {original_size / 1024 / 1024:.2f} MB")
    print(f"Compressed size: {compressed_size / 1024 / 1024:.2f} MB")
    print(f"Compression ratio: {compression_ratio:.1f}%")


def main() -> None:
    """Main function to parse arguments and execute build and packaging tasks."""
    parser = argparse.ArgumentParser(description="Build and archive Hammer 5 Tools.")
    parser.add_argument('--build-all', action='store_true', help="Build Hammer 5 Tools.")
    parser.add_argument('--build-app', action='store_true', help="Build only Hammer 5 Tools.")
    parser.add_argument('--archive', action='store_true', help="Archive the build outputs.")
    parser.add_argument('--fast', action='store_true', help="Use 0 level optimization.")
    channel_group = parser.add_mutually_exclusive_group()
    channel_group.add_argument('--stable', action='store_true', help="Build stable release (default).")
    channel_group.add_argument('--dev', action='store_true', help="Build dev release.")
    args = parser.parse_args()
    channel = 'dev' if args.dev else 'stable'


    overall_start_time = time.time()

    stage_start_time = time.time()
    # Kill processes
    for p in ["Hammer5Tools.exe", "fileedit.exe"]:
        kill_process(p)



    print_elapsed_time("Kill processes", stage_start_time)

    results = []

    try:
        if args.build_all or args.build_app:
            stage_start_time = time.time()
            build_hammer5_tools(fast=args.fast, channel=channel)

            elapsed_time = time.time() - stage_start_time
            results.append(["Hammer 5 Tools Build (Python)", f"{elapsed_time:.2f} seconds"])

            # Build C++ Helper (Handler)
            stage_start_time = time.time()
            build_cpp("fileedit", os.path.join(cur_dir, "launcher"), "fileedit")
            # Move handler to the bundle root
            handler_src = os.path.join(cur_dir, "Hammer5Tools", "fileedit.exe")
            handler_dst = os.path.join(cur_dir, "Hammer5Tools", "fileedit.exe")

            if os.path.exists(handler_src) and handler_src != handler_dst:
                import shutil
                shutil.move(handler_src, handler_dst)

            elapsed_time = time.time() - stage_start_time
            results.append(["C++ Handler Build", f"{elapsed_time:.2f} seconds"])



    except subprocess.CalledProcessError as e:

        print(f"Error during build: {e}")
        return

    output_folder = 'dist'
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)
    zip_output_path = os.path.join(output_folder, 'hammer5tools.zip')

    if args.archive:
        stage_start_time = time.time()
        excluded_files = {
            'hammer5tools.7z',
            'hammer5tools_setup.exe',
            'hammer5tools.zip',
            'settings.ini',
            'Hammer5ToolsInstaller.exe'
        }
        excluded_paths = [
            'SoundEventEditor\\sounds', 
            'SmartPropEditor\\UserPresets',
            'SoundEventEditor\\UserPresets'
        ]
        archive_files('hammer5tools', zip_output_path, excluded_files, excluded_paths)
        elapsed_time = time.time() - stage_start_time
        results.append(["Archiving files", f"{elapsed_time:.2f} seconds"])

        # Inno Setup build removed
        pass

    overall_elapsed_time = time.time() - overall_start_time
    results.append(["Overall process", f"{overall_elapsed_time:.2f} seconds"])

    print(tabulate(results, headers=["Stage", "Elapsed Time"], tablefmt="grid"))


if __name__ == "__main__":
    main()

