import time
from datetime import datetime, timezone
import os
import zipfile
import subprocess
import argparse
from typing import List, Set
from tabulate import tabulate
from src.common import app_version
import re
import sys
cur_dir = os.path.abspath(os.path.dirname(__file__))

external = f"--add-data={os.path.join(cur_dir, 'src', 'external')};src\\external"
print(f"External path: {external}")

# Path to your .NET DLLs
dotnet_dlls = [
    ("Datamodel.NET.dll", "src\\external"),
    ("ValveKeyValue.dll", "src\\external"),
    ("ValvePak.dll", "src\\external"),
    ("ValveResourceFormat.dll", "src\\external"),
    ("ZstdSharp.dll", "src\\external"),
    ("K4os.Compression.LZ4.dll", "src\\external"),
    ("SharpGLTF.Toolkit.dll", "src\\external"),
    ("SharpZstd.Interop.dll", "src\\external"),
    ("SkiaSharp.dll", "src\\external"),
    ("System.IO.Hashing.dll", "src\\external"),
    ("TinyBCSharp.dll", "src\\external"),
    ("TinyEXR.NET.dll", "src\\external")
]


# Path to your .NET DLLs


def print_elapsed_time(stage_name: str, start_time: float) -> None:
    """Prints the elapsed time for a given stage."""
    elapsed_time = time.time() - start_time
    print(f"{stage_name} took {elapsed_time:.2f} seconds")


def kill_process(process_name: str) -> None:
    """Kills a process by its name."""
    subprocess.run(
        ["taskkill", "/F", "/IM", process_name],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL
    )


def find_pycparser_tables():
    """
    Return (lextab_path, yacctab_path) if the pre-generated pycparser parser
    tables exist, or None if they are absent (pycparser >= 3.0 generates them
    lazily at runtime, so absence is normal).

    Search order:
      1. Local .venv / venv
      2. pycparser's own package directory (global installs, CI)
      3. Current working directory (generated by _generate_pycparser_tables)
    """
    try:
        import pycparser as _pycparser
        pycparser_pkg_dir = os.path.dirname(_pycparser.__file__)
    except ImportError:
        pycparser_pkg_dir = None

    candidates = [
        os.path.join(cur_dir, '.venv', 'Lib', 'site-packages', 'pycparser'),
        os.path.join(cur_dir, 'venv', 'Lib', 'site-packages', 'pycparser'),
    ]
    if pycparser_pkg_dir:
        candidates.append(pycparser_pkg_dir)
    candidates.append(cur_dir)  # fallback: generated into cwd

    for base in candidates:
        lextab = os.path.join(base, 'lextab.py')
        yacctab = os.path.join(base, 'yacctab.py')
        if os.path.isfile(lextab) and os.path.isfile(yacctab):
            return lextab, yacctab
    return None


def _generate_pycparser_tables():
    """
    Force pycparser to generate lextab.py and yacctab.py by instantiating
    its C parser with outputdir set to cur_dir so the files land somewhere
    predictable regardless of whether the package dir is writable.
    """
    try:
        import pycparser
        import pycparser.ply.lex as lex
        import pycparser.ply.yacc as yacc
        # Monkey-patch outputdir so tables land in cur_dir
        _orig_lex = lex.lex
        _orig_yacc = yacc.yacc

        def _lex(*a, **kw):
            kw.setdefault('outputdir', cur_dir)
            return _orig_lex(*a, **kw)

        def _yacc(*a, **kw):
            kw.setdefault('outputdir', cur_dir)
            return _orig_yacc(*a, **kw)

        lex.lex = _lex
        yacc.yacc = _yacc
        try:
            from pycparser import c_parser
            c_parser.CParser()
            print("pycparser tables generated.")
        finally:
            lex.lex = _orig_lex
            yacc.yacc = _orig_yacc
    except Exception as e:
        print(f"Warning: could not pre-generate pycparser tables: {e}")


def build_cpp(project: str, src_dir: str, output_name: str) -> None:
    """Builds a C++ project using CMake."""
    build_dir = os.path.join(cur_dir, f"build_cpp_{project}")
    os.makedirs(build_dir, exist_ok=True)
    try:
        # Let CMake choose the best generator for the system
        subprocess.run(["cmake", "-S", src_dir, "-B", build_dir,
                        "-DCMAKE_BUILD_TYPE=Release"], check=True)
        subprocess.run(["cmake", "--build", build_dir, "--config", "Release"], check=True)
        
        # Copy exe to hammer5tools/
        # CMake might put the exe in build_dir or build_dir/Release (for MSVC)
        src_exe = os.path.join(build_dir, f"{output_name}.exe")
        if not os.path.exists(src_exe):
            src_exe = os.path.join(build_dir, "Release", f"{output_name}.exe")
            
        if not os.path.exists(src_exe):
            raise FileNotFoundError(f"Could not find built executable at {src_exe}")

        dst_exe = os.path.join(cur_dir, "out_hammer5tools", f"{output_name}.exe")

        os.makedirs(os.path.dirname(dst_exe), exist_ok=True)
        import shutil
        shutil.copy2(src_exe, dst_exe)
        print(f"Successfully built and copied {output_name}.exe")
    except subprocess.CalledProcessError as e:
        print(f"Error building C++ project {project}: {e}")
        raise


def build_app_pyinstaller(fast=False) -> None:
    """Builds the Python application using PyInstaller."""
    # Try to locate pre-generated pycparser tables; generate them if absent.
    tables = find_pycparser_tables()
    if tables is None:
        _generate_pycparser_tables()
        tables = find_pycparser_tables()

    pyinstaller_cmd = [
        sys.executable, '-m', 'PyInstaller',
        '--name=h5t',

        '--noupx',
        '--distpath=out_hammer5tools',

        '--noconfirm',
        '--onedir',
        '--windowed',
        '--paths=.',
        '--hidden-import=resources_rc',
        '--hidden-import=widgets',
        '--collect-all=src',
        '--collect-all=keyvalues3',
        '--collect-submodules=pycparser',
        '--hidden-import=PySide6.QtNetwork',
        '--hidden-import=PySide6.QtMultimedia',
        '--hidden-import=PySide6.QtMultimediaWidgets',
        '--hidden-import=cffi',
        '--collect-submodules=cffi',
        '--hidden-import=clr_loader',
        '--collect-submodules=clr_loader',
        '--optimize=0',
        '--icon=src/appicon.ico',
        '--add-data=src/appicon.ico;.',
        '--add-data=src/images;images/',
        '--add-data=src/styles;styles/',
        '--add-data=Hammer5Tools;defaults/',
        '--exclude-module=PyQt5',
        '--exclude-module=numba',
        '--exclude-module=scipy',
        '--exclude-module=pandas',
        '--exclude-module=tabulate',
        external,
        *[f'--add-binary=src{os.sep}external{os.sep}{dll};external{os.sep}{dll}' for dll, _ in dotnet_dlls],
        'src/main.py'
    ]

    if tables:
        lextab_path, yacctab_path = tables
        pyinstaller_cmd += [
            f'--add-data={lextab_path};pycparser',
            f'--add-data={yacctab_path};pycparser',
        ]
    
    subprocess.run(pyinstaller_cmd, check=True)


def build_app_nuitka() -> None:
    """Builds the Python application using Nuitka."""
    nuitka_cmd = [
        sys.executable, "-m", "nuitka",
        "--standalone",
        "--plugin-enable=pyside6",
        "--windows-console-mode=disable",

        f"--output-dir={os.path.join(cur_dir, 'out_hammer5tools')}",
        "--output-filename=h5t.exe",
        "--remove-output",
        "--no-pyi-file",
        "--include-package=keyvalues3",

        "--include-package=pycparser",
        "--include-package=cffi",
        "--include-package=clr_loader",
        f"--include-data-file={os.path.join(cur_dir, 'src', 'appicon.ico')}=appicon.ico",
        f"--include-data-dir={os.path.join(cur_dir, 'src', 'images')}=images",
        f"--include-data-dir={os.path.join(cur_dir, 'src', 'styles')}=styles",
        f"--include-data-dir={os.path.join(cur_dir, 'Hammer5Tools')}=defaults",
        f"--include-data-dir={os.path.join(cur_dir, 'src', 'external')}=src/external",
        f"--windows-icon-from-ico={os.path.join(cur_dir, 'src', 'appicon.ico')}",
    ]

    # Add .NET DLLs as binaries
    for dll, _ in dotnet_dlls:
        dll_path = os.path.join(cur_dir, "src", "external", dll)
        nuitka_cmd.append(f"--include-data-file={dll_path}=external/{dll}")

    # Add pycparser tables if found
    tables = find_pycparser_tables()
    if tables:
        lextab_path, yacctab_path = tables
        nuitka_cmd.append(f"--include-data-file={lextab_path}=pycparser/lextab.py")
        nuitka_cmd.append(f"--include-data-file={yacctab_path}=pycparser/yacctab.py")

    nuitka_cmd.append(os.path.join(cur_dir, "src", "main.py"))

    
    subprocess.run(nuitka_cmd, check=True)

    # Nuitka creates h5t.dist folder, we need to rename it to app
    dist_root = 'out_hammer5tools'
    nuitka_dist_path = os.path.join(dist_root, 'main.dist')

    target_app_path = os.path.join(dist_root, 'app')
    
    if os.path.exists(nuitka_dist_path):
        import shutil
        if os.path.exists(target_app_path):
            shutil.rmtree(target_app_path)
        os.rename(nuitka_dist_path, target_app_path)
        # Rename main.exe to h5t.exe if Nuitka named it main.exe
        main_exe = os.path.join(target_app_path, "main.exe")
        h5t_exe = os.path.join(target_app_path, "h5t.exe")
        if os.path.exists(main_exe):
            os.rename(main_exe, h5t_exe)


def build_hammer5_tools(fast=False, channel='stable', method='pyinstaller') -> None:
    # Phase 0: Clean up the Hammer5Tools template folder to avoid recursive bundling

    # (We clean internal files but keep the source folder itself)
    template_dir = os.path.join(cur_dir, 'Hammer5Tools')
    if os.path.exists(template_dir):
        import shutil
        for item in ['app', 'Hammer5Tools.exe', 'Hammer5ToolsUpdater.exe', 'version.txt']:
            path = os.path.join(template_dir, item)
            if os.path.exists(path):
                if os.path.isdir(path):
                    shutil.rmtree(path)
                else:
                    os.remove(path)
        print(f"Cleaned up template directory: {template_dir}")


    if method == 'nuitka':
        build_app_nuitka()
    else:
        build_app_pyinstaller(fast=fast)


    # Rename output folder to 'app' for the new layout
    dist_root = 'out_hammer5tools'
    app_bundle_path = os.path.join(dist_root, 'h5t')

    target_app_path = os.path.join(dist_root, 'app')
    
    import shutil
    import time

    def safe_rmtree(path, retries=5):
        for i in range(retries):
            try:
                if os.path.exists(path):
                    shutil.rmtree(path)
                return
            except Exception:
                if i == retries - 1: raise
                time.sleep(1)

    def safe_rename(src, dst, retries=5):
        for i in range(retries):
            try:
                if os.path.exists(dst):
                    safe_rmtree(dst)
                os.rename(src, dst)
                return
            except Exception:
                if i == retries - 1: raise
                time.sleep(1)

    if method == 'pyinstaller':
        # Rename output folder to 'app' for the new layout
        if os.path.exists(app_bundle_path):
            safe_rename(app_bundle_path, target_app_path)
            print(f"Renamed {app_bundle_path} to {target_app_path}")



    # Phase 3: Write version.txt into the bundle (4-line format: version, channel, build_date, commit_sha)
    version_file_path = os.path.join(target_app_path, 'version.txt')
    build_date = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
    try:
        commit_sha = subprocess.check_output(
            ['git', 'rev-parse', 'HEAD'], text=True, cwd=cur_dir
        ).strip()
    except Exception:
        commit_sha = 'unknown'
    with open(version_file_path, 'w', encoding='utf-8') as f:
        f.write(f"{app_version}\n{channel}\n{build_date}\n{commit_sha}\n")
    print(f"Wrote version.txt to {version_file_path} (channel={channel}, date={build_date}, sha={commit_sha[:7]})")

    # Copy to dist/ root so CI can upload it as a standalone release asset
    import shutil as _shutil
    dist_version_path = os.path.join(cur_dir, 'dist', 'version.txt')
    os.makedirs(os.path.dirname(dist_version_path), exist_ok=True)
    _shutil.copy(version_file_path, dist_version_path)
    print(f"Copied version.txt to {dist_version_path}")


def archive_files(
    folder_path: str,
    output_path: str,
    excluded_files: Set[str],
    excluded_paths: List[str]
) -> None:
    """Archives files from a folder into a zip file with maximum compression, excluding specified files and paths."""

    def should_exclude(file_name: str, file_path: str) -> bool:
        if file_name in excluded_files:
            return True
        for excluded_path in excluded_paths:
            if excluded_path in os.path.normpath(file_path):
                return True
        return False

    with zipfile.ZipFile(output_path, 'w', compression=zipfile.ZIP_DEFLATED, compresslevel=6) as archive:
        for root, _, files in os.walk(folder_path):
            for file in files:
                file_path = os.path.join(root, file)
                rel_path = os.path.relpath(file_path, folder_path)
                if should_exclude(file, rel_path):
                    continue
                try:
                    archive.write(file_path, rel_path)
                except OSError as e:
                    print(f"Warning: Could not add file {file_path}: {e}")

    original_size = sum(
        os.path.getsize(os.path.join(root, file))
        for root, _, files in os.walk(folder_path)
        for file in files
        if not should_exclude(file, os.path.join(root, file))
    )
    compressed_size = os.path.getsize(output_path)
    compression_ratio = (1 - compressed_size / original_size) * 100 if original_size > 0 else 0

    print(f"Archived files to {output_path}")
    print(f"Original size: {original_size / 1024 / 1024:.2f} MB")
    print(f"Compressed size: {compressed_size / 1024 / 1024:.2f} MB")
    print(f"Compression ratio: {compression_ratio:.1f}%")


def main() -> None:
    """Main function to parse arguments and execute build and packaging tasks."""
    parser = argparse.ArgumentParser(description="Build and archive Hammer 5 Tools.")
    parser.add_argument('--build-all', action='store_true', help="Build Hammer 5 Tools.")
    parser.add_argument('--build-app', action='store_true', help="Build only Hammer 5 Tools.")
    parser.add_argument('--archive', action='store_true', help="Archive the build outputs.")
    parser.add_argument('--fast', action='store_true', help="Use 0 level optimization.")
    channel_group = parser.add_mutually_exclusive_group()
    channel_group.add_argument('--stable', action='store_true', help="Build stable release (default).")
    channel_group.add_argument('--dev', action='store_true', help="Build dev release.")
    parser.add_argument('--nuitka', action='store_true', help="Use Nuitka instead of PyInstaller.")
    args = parser.parse_args()
    channel = 'dev' if args.dev else 'stable'
    build_method = 'nuitka' if args.nuitka else 'pyinstaller'


    overall_start_time = time.time()

    stage_start_time = time.time()
    # Kill processes
    for p in ["Hammer5Tools.exe", "h5t.exe", "h5t_replacer.exe"]:
        kill_process(p)

    print_elapsed_time("Kill processes", stage_start_time)

    results = []

    try:
        if args.build_all or args.build_app:
            stage_start_time = time.time()
            build_hammer5_tools(fast=args.fast, channel=channel, method=build_method)

            elapsed_time = time.time() - stage_start_time
            results.append(["Hammer 5 Tools Build (Python)", f"{elapsed_time:.2f} seconds"])

            # Build C++ Unified Launcher/Updater
            stage_start_time = time.time()
            build_cpp("Hammer5Tools", os.path.join(cur_dir, "launcher"), "Hammer5Tools")
            elapsed_time = time.time() - stage_start_time
            results.append(["Unified C++ Executable Build", f"{elapsed_time:.2f} seconds"])

            # Rename out_hammer5tools back to hammer5tools for final output
            # (We used out_hammer5tools to avoid case-insensitive rm -r collision with Hammer5Tools source)
            final_root = os.path.join(cur_dir, 'hammer5tools')
            if os.path.exists(final_root):
                import shutil
                shutil.rmtree(final_root)
            os.rename(os.path.join(cur_dir, 'out_hammer5tools'), final_root)

    except subprocess.CalledProcessError as e:

        print(f"Error during build: {e}")
        return

    output_folder = 'dist'
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)
    zip_output_path = os.path.join(output_folder, 'hammer5tools.zip')

    if args.archive:
        stage_start_time = time.time()
        excluded_files = {
            'hammer5tools.7z',
            'hammer5tools_setup.exe',
            'hammer5tools.zip',
            'settings.ini',
            'Hammer5ToolsInstaller.exe'
        }
        excluded_paths = [
            'SoundEventEditor\\sounds', 
            'SmartPropEditor\\UserPresets',
            'SoundEventEditor\\UserPresets'
        ]
        archive_files('hammer5tools', zip_output_path, excluded_files, excluded_paths)
        elapsed_time = time.time() - stage_start_time
        results.append(["Archiving files", f"{elapsed_time:.2f} seconds"])

        # Modify installer.iss by copying to a temporary file, updating version, compiling, then deleting tmp file
        import shutil
        tmp_iss_path = os.path.join(cur_dir, 'installer_tmp.iss')
        iss_path = os.path.join(cur_dir, 'installer.iss')
        # Copy original to tmp
        shutil.copyfile(iss_path, tmp_iss_path)
        # Read tmp file content
        with open(tmp_iss_path, 'r', encoding='utf-8') as f:
            content = f.read()
        # Replace the AppVersion line in the [Setup] section
        content = re.sub(r'^(AppVersion\s*=\s*).*$',
                         rf'\g<1>{app_version}',
                         content,
                         flags=re.MULTILINE)
        # Write back the modified content to tmp file
        with open(tmp_iss_path, 'w', encoding='utf-8') as f:
            f.write(content)
        # Build installer using Inno Setup Compiler (ISCC) with tmp file
        try:
            build_installer_start = time.time()
            subprocess.run(['C:\Program Files (x86)\Inno Setup 6\ISCC.exe', tmp_iss_path], check=True)
            build_installer_elapsed = time.time() - build_installer_start
            results.append(["Build installer", f"{build_installer_elapsed:.2f} seconds"])
        except Exception as e:
            print(f"Error building installer: {e}")
            results.append(["Build installer", f"Failed: {e}"])
        finally:
            # Delete the temporary file
            try:
                os.remove(tmp_iss_path)
            except Exception as e:
                print(f"Warning: Could not delete temporary installer file: {e}")

    overall_elapsed_time = time.time() - overall_start_time
    results.append(["Overall process", f"{overall_elapsed_time:.2f} seconds"])

    print(tabulate(results, headers=["Stage", "Elapsed Time"], tablefmt="grid"))


if __name__ == "__main__":
    main()

