"""
UE engine default meshes (/Engine/BasicShapes/*) have no bulk-export FBX — they
live in the engine install, not the project. Rather than emitting a vmdl that
points at a missing file, we procedurally generate matching primitive geometry
as an OBJ (which the Source 2 resource compiler imports) and wrap it in a vmdl.

Dimensions match Unreal's BasicShapes so a placed actor's scale produces the
same final size in Source 2:
  Plane    100 x 100, centered, facing +Z
  Cube     100 cube, centered
  Sphere   radius 50 (100 diameter), centered
  Cylinder radius 50, height 100, base at Z=0
  Cone     radius 50, height 100, base at Z=0
"""

import math
import os

_BASIC_SHAPES = ("plane", "cube", "sphere", "cylinder", "cone")

# Real UE BasicShapes FBX bundled with the program (exported from the engine).
# Preferred over the procedural OBJ fallback so the geometry matches UE exactly
# (correct pivots, UVs, and UCX collision).
_BUNDLED_DIR = os.path.join(os.path.dirname(__file__), "assets", "basicshapes")


def bundled_fbx_for(ue_mesh_path: str):
    """Absolute path to the bundled FBX for a UE BasicShape, or None."""
    shape = _shape_of(ue_mesh_path)
    if shape is None:
        return None
    p = os.path.join(_BUNDLED_DIR, f"{shape}.fbx")
    return p if os.path.isfile(p) else None


def is_engine_mesh(ue_mesh_path: str) -> bool:
    p = ue_mesh_path.lower()
    return "/engine/basicshapes/" in p and _shape_of(ue_mesh_path) is not None


def _shape_of(ue_mesh_path: str):
    stem = ue_mesh_path.split(".", 1)[0].rstrip("/").rsplit("/", 1)[-1].lower()
    return stem if stem in _BASIC_SHAPES else None


# --------------------------------------------------------------------------
# OBJ primitive generators (return the OBJ text)
# --------------------------------------------------------------------------

def _obj(verts, faces, normals=None, uvs=None) -> str:
    lines = ["# generated by Hammer5Tools Unreal Converter"]
    for x, y, z in verts:
        lines.append(f"v {x:.4f} {y:.4f} {z:.4f}")
    for u, v in (uvs or []):
        lines.append(f"vt {u:.4f} {v:.4f}")
    for nx, ny, nz in (normals or []):
        lines.append(f"vn {nx:.4f} {ny:.4f} {nz:.4f}")
    for f in faces:
        lines.append("f " + " ".join(f))
    return "\n".join(lines) + "\n"


def _plane() -> str:
    verts = [(-50, -50, 0), (50, -50, 0), (50, 50, 0), (-50, 50, 0)]
    uvs = [(0, 0), (1, 0), (1, 1), (0, 1)]
    normals = [(0, 0, 1)]
    faces = [[f"{i+1}/{i+1}/1" for i in range(4)]]
    return _obj(verts, faces, normals, uvs)


def _cube() -> str:
    h = 50.0
    verts = [(-h, -h, -h), (h, -h, -h), (h, h, -h), (-h, h, -h),
             (-h, -h, h), (h, -h, h), (h, h, h), (-h, h, h)]
    normals = [(0, 0, -1), (0, 0, 1), (0, -1, 0), (1, 0, 0), (0, 1, 0), (-1, 0, 0)]
    quads = [([1, 4, 3, 2], 1), ([5, 6, 7, 8], 2), ([1, 2, 6, 5], 3),
             ([2, 3, 7, 6], 4), ([3, 4, 8, 7], 5), ([4, 1, 5, 8], 6)]
    faces = [[f"{v}//{n}" for v in vs] for vs, n in quads]
    return _obj(verts, faces, normals)


def _sphere(rings=16, segments=24, r=50.0) -> str:
    verts, normals, faces = [], [], []
    for i in range(rings + 1):
        theta = math.pi * i / rings
        for j in range(segments + 1):
            phi = 2 * math.pi * j / segments
            x = r * math.sin(theta) * math.cos(phi)
            y = r * math.sin(theta) * math.sin(phi)
            z = r * math.cos(theta)
            verts.append((x, y, z))
            n = math.sqrt(x * x + y * y + z * z) or 1
            normals.append((x / n, y / n, z / n))
    stride = segments + 1
    for i in range(rings):
        for j in range(segments):
            a = i * stride + j + 1
            b = a + 1
            c = a + stride
            d = c + 1
            faces.append([f"{a}//{a}", f"{c}//{c}", f"{d}//{d}", f"{b}//{b}"])
    return _obj(verts, faces, normals)


def _cylinder(segments=24, r=50.0, h=100.0) -> str:
    verts, normals, faces = [], [], []
    # side rings (base z=0, top z=h)
    for z in (0.0, h):
        for j in range(segments + 1):
            phi = 2 * math.pi * j / segments
            verts.append((r * math.cos(phi), r * math.sin(phi), z))
            normals.append((math.cos(phi), math.sin(phi), 0))
    stride = segments + 1
    for j in range(segments):
        a = j + 1
        b = a + 1
        c = a + stride
        d = c + 1
        faces.append([f"{a}//{a}", f"{c}//{c}", f"{d}//{d}", f"{b}//{b}"])
    # caps (fans)
    base_c = len(verts) + 1
    verts.append((0, 0, 0)); normals.append((0, 0, -1))
    top_c = len(verts) + 1
    verts.append((0, 0, h)); normals.append((0, 0, 1))
    for j in range(segments):
        a = j + 1
        b = a + 1
        faces.append([f"{base_c}//{base_c}", f"{b}//{base_c}", f"{a}//{base_c}"])
        ta = stride + j + 1
        tb = ta + 1
        faces.append([f"{top_c}//{top_c}", f"{ta}//{top_c}", f"{tb}//{top_c}"])
    return _obj(verts, faces, normals)


def _cone(segments=24, r=50.0, h=100.0) -> str:
    verts, normals, faces = [], [], []
    for j in range(segments + 1):
        phi = 2 * math.pi * j / segments
        verts.append((r * math.cos(phi), r * math.sin(phi), 0.0))
        normals.append((math.cos(phi), math.sin(phi), 0.4))
    apex = len(verts) + 1
    verts.append((0, 0, h)); normals.append((0, 0, 1))
    base_c = len(verts) + 1
    verts.append((0, 0, 0)); normals.append((0, 0, -1))
    for j in range(segments):
        a = j + 1
        b = a + 1
        faces.append([f"{a}//{a}", f"{b}//{b}", f"{apex}//{apex}"])
        faces.append([f"{base_c}//{base_c}", f"{b}//{base_c}", f"{a}//{base_c}"])
    return _obj(verts, faces, normals)


_GENERATORS = {
    "plane": _plane, "cube": _cube, "sphere": _sphere,
    "cylinder": _cylinder, "cone": _cone,
}


def generate_engine_mesh_obj(ue_mesh_path: str, out_path: str):
    """
    Write the OBJ for a UE engine BasicShape referenced by ue_mesh_path. Returns
    the OBJ path, or None if the mesh isn't a recognized engine primitive.
    """
    shape = _shape_of(ue_mesh_path)
    if shape is None:
        return None
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, "w") as f:
        f.write(_GENERATORS[shape]())
    return out_path
