<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Hammer5Tools.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../../Presets/SmartPropEditor/Presets/**/*.vsmart" Link="Fixtures/%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <Compile Include="../Hammer5Tools.NativeAot.Tests/SmartProps/SmartPropEvaluatorTests.cs" Link="SmartProps/SmartPropEvaluatorTests.cs" />
    <PackageReference Include="TUnit" />
  </ItemGroup>

</Project>
