using System.Numerics;
using Datamodel;

namespace SourcePorter.Core.Vmap;

/// <summary>
/// Removes redundant <c>CMapGroup</c> wrappers from a map's node tree. <c>source1import</c>
/// (and the decompile path) leave behind a lot of groups that contain a <b>single</b> object —
/// a group of one is pure overhead: every <c>CMapGroup</c> is a full Datamodel element with its
/// own id / node-id / editor attributes, so thousands of one-child wrappers bloat the
/// <c>.vmap</c> for no organisational benefit. This tool:
/// <list type="bullet">
///   <item><b>flattens single-child groups</b> — replaces a one-child <c>CMapGroup</c> with its
///   lone child in the parent's child list (the child keeps its position); and</item>
///   <item><b>drops empty groups</b> — a <c>CMapGroup</c> with no children is removed entirely.</item>
/// </list>
/// <para>
/// It runs <b>bottom-up</b> (post-order), so a group whose only child is itself a now-flattened
/// group collapses too — e.g. <c>group → group → mesh</c> reduces to just <c>mesh</c>.
/// </para>
/// <para>
/// <b>Safety.</b> A <c>CMapGroup</c> is a transform node (it carries <c>origin</c>/<c>angles</c>/
/// <c>scales</c>, with children in the group's local space), so collapsing one that has a
/// non-identity transform would move its child. We therefore only collapse groups whose transform
/// is trivial (identity) — which is exactly what the importer emits for its organisational
/// wrappers; any group the user actually transformed is left untouched. Groups that are the
/// <c>target</c> of a <c>CMapInstance</c> are also preserved (removing them would break the
/// instance). Only the exact class <c>CMapGroup</c> is touched — structural subclasses such as
/// <c>CMapWorldLayer</c> are never collapsed.
/// </para>
/// The operation is idempotent: a second run finds nothing left to flatten.
/// </summary>
public static class VmapGroupFlattener
{
    /// <summary>Outcome of a flatten pass over the addon's maps.</summary>
    public sealed record Result(int FilesChanged, int GroupsFlattened, int EmptyGroupsRemoved)
    {
        public bool DidAnything => GroupsFlattened > 0 || EmptyGroupsRemoved > 0;
    }

    /// <summary>
    /// Flattens single-child / empty groups in every <c>.vmap</c> under
    /// <paramref name="addonContentMapsDir"/> (the main map and its prefab sub-maps). Each changed
    /// file is backed up first; the backup is dropped on success (the <c>.vmap</c> is regenerated by
    /// every import). Maps are loaded in-memory so the (binary DMX) file handle isn't held while we
    /// overwrite it.
    /// </summary>
    public static Result FlattenAddon(
        string addonContentMapsDir, Action<string>? log = null, CancellationToken ct = default)
    {
        log?.Invoke("▶ Flatten single-child groups: removing redundant CMapGroup wrappers…");
        if (!Directory.Exists(addonContentMapsDir))
        {
            log?.Invoke($"  No maps dir at {addonContentMapsDir} — skipping.");
            return new Result(0, 0, 0);
        }

        int filesChanged = 0, flattened = 0, empty = 0;
        foreach (var vmap in Directory.EnumerateFiles(addonContentMapsDir, "*.vmap", SearchOption.AllDirectories))
        {
            ct.ThrowIfCancellationRequested();

            VmapDocument doc;
            try { doc = VmapDocument.LoadInMemory(vmap); }
            catch (Exception ex) { log?.Invoke($"  WARNING: couldn't read {Path.GetFileName(vmap)}: {ex.Message}"); continue; }

            var (gf, er) = Flatten(doc, ct);
            if (gf == 0 && er == 0)
                continue;

            var backup = VmapBackup.Backup(vmap, log);
            doc.Save();
            try { File.Delete(backup); }
            catch (Exception ex) { log?.Invoke($"  WARNING: could not delete backup {Path.GetFileName(backup)}: {ex.Message}"); }

            filesChanged++;
            flattened += gf;
            empty += er;
            log?.Invoke($"  {Path.GetFileName(vmap)}: flattened {gf} single-child group(s)" +
                        (er > 0 ? $", removed {er} empty group(s)" : "") + ".");
        }

        if (filesChanged == 0)
            log?.Invoke("  No redundant single-child groups found.");
        else
            log?.Invoke($"  Flatten complete: {flattened} group(s) collapsed across {filesChanged} file(s).");
        return new Result(filesChanged, flattened, empty);
    }

    /// <summary>
    /// Flattens single-child / empty groups in one loaded document, in place. Returns
    /// <c>(groupsFlattened, emptyGroupsRemoved)</c>. The caller saves the document afterwards.
    /// </summary>
    public static (int GroupsFlattened, int EmptyGroupsRemoved) Flatten(VmapDocument doc, CancellationToken ct = default)
    {
        var children = doc.TryGetWorldChildren();
        if (children is null)
            return (0, 0);

        var protectedGroups = CollectInstanceTargets(doc.Model.Root);
        var visited = new HashSet<Element>();
        int flattened = 0, empty = 0;

        void Process(ElementArray arr)
        {
            // Recurse into every node's children first so nested groups collapse bottom-up.
            foreach (var node in arr.ToList())
            {
                ct.ThrowIfCancellationRequested();
                if (node is null || !visited.Add(node))
                    continue;
                if (ChildrenOf(node) is { } sub)
                    Process(sub);
            }

            // Then collapse redundant groups at this level (children already cleaned up above).
            foreach (var node in arr.ToList())
            {
                if (node is null || !IsCollapsibleGroup(node, protectedGroups))
                    continue;

                var kids = ChildrenOf(node);
                var count = kids?.Count ?? 0;
                if (count == 1)
                {
                    var idx = arr.IndexOf(node);
                    if (idx >= 0)
                    {
                        arr[idx] = kids![0]; // lift the lone child into the group's slot
                        flattened++;
                    }
                }
                else if (count == 0)
                {
                    arr.Remove(node);
                    empty++;
                }
            }
        }

        Process(children);
        return (flattened, empty);
    }

    /// <summary>The child-node array of a node, or null if it has none.</summary>
    private static ElementArray? ChildrenOf(Element e) =>
        e.ContainsKey("children") && e["children"] is ElementArray a ? a : null;

    private static bool IsCollapsibleGroup(Element e, HashSet<Element> protectedGroups) =>
        string.Equals(e.ClassName, "CMapGroup", StringComparison.Ordinal)
        && !protectedGroups.Contains(e)
        && IsTrivialTransform(e);

    /// <summary>True when the node has no (or default) <c>origin</c>/<c>angles</c>/<c>scales</c> —
    /// i.e. collapsing it won't move its child.</summary>
    private static bool IsTrivialTransform(Element e)
    {
        if (e.ContainsKey("origin") && e["origin"] is Vector3 o && o != Vector3.Zero)
            return false;
        if (e.ContainsKey("scales") && e["scales"] is Vector3 s && s != Vector3.One)
            return false;
        if (e.ContainsKey("angles") && e["angles"] is QAngle a && (a.Pitch != 0f || a.Yaw != 0f || a.Roll != 0f))
            return false;
        return true;
    }

    /// <summary>Collects every <c>CMapGroup</c> referenced as the <c>target</c> of a
    /// <c>CMapInstance</c> — those must not be collapsed/removed or the instance breaks.</summary>
    private static HashSet<Element> CollectInstanceTargets(Element? root)
    {
        var targets = new HashSet<Element>();
        var seen = new HashSet<Element>();

        void Walk(Element? e)
        {
            if (e is null || !seen.Add(e))
                return;
            if (string.Equals(e.ClassName, "CMapInstance", StringComparison.Ordinal)
                && e.ContainsKey("target") && e["target"] is Element target)
                targets.Add(target);
            foreach (var kv in e)
            {
                if (kv.Value is Element c) Walk(c);
                else if (kv.Value is ElementArray a)
                    foreach (var x in a) Walk(x);
            }
        }

        Walk(root);
        return targets;
    }
}
