<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><IsTestProject>true</IsTestProject></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../GUI/Hammer5Tools.csproj" />
    <PackageReference Include="TUnit" />
    <PackageReference Include="Avalonia.Headless" />
  </ItemGroup>
</Project>
