<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>Hammer5Tools.Native</AssemblyName>
    <RootNamespace>Hammer5Tools.Native</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PublishAot>true</PublishAot>
    <NativeLib>Shared</NativeLib>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hammer5Tools.Core\Hammer5Tools.Core.csproj" />
    <ProjectReference Include="..\SourcePorter.Core\SourcePorter.Core.csproj" />
  </ItemGroup>

</Project>
