"""Default `.gitignore` and `.gitattributes` for a Counter-Strike 2 addon repo.

Lifted from a shipped CS2 map addon, so the LFS list already covers what Hammer,
Blender, Substance and ZBrush drop into a content tree — a `.vmap` committed
without LFS is a multi-hundred-megabyte blob in every clone forever.

Embedded as strings rather than shipped as data files: the packaged build copies
`.py` modules and nothing else out of this package.
"""
import os

GITIGNORE = '''#3D source files

*_autosave*
*.blend1
*.bak
*.blend2
*.blend3
*.blend4
*.assbin
*_highpoly.fbx
*_highpoly.obj




# Visual Studio 2015 user specific files
.vs/


*.log
# Compiled Object files
*.slo
*.lo
*.o
*.obj

# Precompiled Headers
*.gch
*.pch

# Compiled Dynamic libraries
*.so
*.dylib
*.dll

# Fortran module files
*.mod

# Compiled Static libraries
*.lai
*.la
*.a
*.lib

# Executables
*.exe
*.out
*.app
*.ipa

# These project files can be generated by the engine
*.xcodeproj
*.xcworkspace
*.sln
*.suo
*.opensdf
*.sdf
*.VC.db
*.VC.opendb

# Precompiled Assets
SourceArt/**/*.png
SourceArt/**/*.tga

# Binary Files
Binaries/*
Plugins/*/Binaries/*

# Builds
Build/*

# Whitelist PakBlacklist-<BuildConfiguration>.txt files
!Build/*/
Build/*/**
!Build/*/PakBlacklist*.txt

# Don't ignore icon files in Build
!Build/**/*.ico

# Built data for maps
*_BuiltData.uasset

# Configuration files generated by the Editor
Saved/*

# Compiled source files for the engine to use
Intermediate/*
Plugins/*/Intermediate/*

# Cache files for the editor to use
DerivedDataCache/*
.diversion
.ap
*.painter_lock
_buildlog.txt
*.sbk
'''

GITATTRIBUTES = '''# Image Files
*.exr filter=lfs diff=lfs merge=lfs -text
*.hdr filter=lfs diff=lfs merge=lfs -text
*.jpg filter=lfs diff=lfs merge=lfs -text
*.png filter=lfs diff=lfs merge=lfs -text
*.psd filter=lfs diff=lfs merge=lfs -text
*.tga filter=lfs diff=lfs merge=lfs -text
*.tif filter=lfs diff=lfs merge=lfs -text
*.tiff filter=lfs diff=lfs merge=lfs -text
# 3D Assets and Modeling Files
*.assbin filter=lfs diff=lfs merge=lfs -text
*.blend filter=lfs diff=lfs merge=lfs -text
*.blend1 filter=lfs diff=lfs merge=lfs -text
*.blend2 filter=lfs diff=lfs merge=lfs -text
*.blend3 filter=lfs diff=lfs merge=lfs -text
*.blend4 filter=lfs diff=lfs merge=lfs -text
*.fbx filter=lfs diff=lfs merge=lfs -text
*.obj filter=lfs diff=lfs merge=lfs -text
*.sbs filter=lfs diff=lfs merge=lfs -text
*.sbsar filter=lfs diff=lfs merge=lfs -text
*.spsm filter=lfs diff=lfs merge=lfs -text
*.tbscene filter=lfs diff=lfs merge=lfs -text
*.zpr filter=lfs diff=lfs merge=lfs -text
*.ztl filter=lfs diff=lfs merge=lfs -text
# Archives
*.rar filter=lfs diff=lfs merge=lfs -text
*.zip filter=lfs diff=lfs merge=lfs -text
# Audio and Video Files
*.mp3 filter=lfs diff=lfs merge=lfs -text
*.mp4 filter=lfs diff=lfs merge=lfs -text
*.ogg filter=lfs diff=lfs merge=lfs -text
*.wav filter=lfs diff=lfs merge=lfs -text
# Game Engine Files
*.anim filter=lfs diff=lfs merge=lfs -text
*.asset filter=lfs diff=lfs merge=lfs -text
*.controller filter=lfs diff=lfs merge=lfs -text
*.mat filter=lfs diff=lfs merge=lfs -text
*.prefab filter=lfs diff=lfs merge=lfs -text
*.ptx filter=lfs diff=lfs merge=lfs -text
*.spp filter=lfs diff=lfs merge=lfs -text
*.unity filter=lfs diff=lfs merge=lfs -text
*.unitypackage filter=lfs diff=lfs merge=lfs -text
*.vmap filter=lfs diff=lfs merge=lfs -text
*.vpk filter=lfs diff=lfs merge=lfs -text
*.vtex filter=lfs diff=lfs merge=lfs -text
# Other Binary Files
*.bak filter=lfs diff=lfs merge=lfs -text
*.dll filter=lfs diff=lfs merge=lfs -text
*.dmx filter=lfs diff=lfs merge=lfs -text
*.exe filter=lfs diff=lfs merge=lfs -text
*.pur filter=lfs diff=lfs merge=lfs -text
*.radgen filter=lfs diff=lfs merge=lfs -text
*.tor filter=lfs diff=lfs merge=lfs -text
'''


def write_defaults(repo_dir, gitignore=True, gitattributes=True):
    """Write the default config files into `repo_dir`. Returns the names written.

    An existing file is never overwritten — a repo set up against an addon that
    already carries hand-tuned rules must keep them.
    """
    written = []
    for name, text, wanted in ((".gitignore", GITIGNORE, gitignore),
                               (".gitattributes", GITATTRIBUTES, gitattributes)):
        path = os.path.join(repo_dir, name)
        if not wanted or os.path.exists(path):
            continue
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        written.append(name)
    return written


def lfs_patterns():
    """The `*.ext` patterns GITATTRIBUTES routes through Git LFS."""
    return [line.split(None, 1)[0] for line in GITATTRIBUTES.splitlines()
            if "filter=lfs" in line]


def _demo():
    import tempfile
    assert "*.vmap" in lfs_patterns()
    assert "*.png" in lfs_patterns()
    d = tempfile.mkdtemp(prefix="h5t_gittpl_")
    assert write_defaults(d) == [".gitignore", ".gitattributes"]
    assert write_defaults(d) == []          # never clobbers what is already there
    assert os.path.getsize(os.path.join(d, ".gitattributes")) > 0
    print("templates self-check OK")


if __name__ == "__main__":
    _demo()
