"""
Property tooltips and element descriptions extracted from CS2 Valve Schema.
"""

import os

property_tooltips = {
    "m_bEnabled": "Is this element enabled? If not enabled, this element will not be evaluated and will have no effect on the result.",
    "m_sLabel": "Optional text that will appear in the outliner to help organize Smart Prop elements and communicate their purpose to other users.",
    "m_nElementID": "Unique monotonic integer identifier for editor state. Suppressed from standard properties.",
    "m_SelectionCriteria": "Collection of logical conditions and filters that must be met for the element to be processed.",
    "m_Modifiers": "Array of state alterations (transforms, orienting, etc.) applied to the element.",
    "m_AllowedMaterialAttributes": "List of material attributes on which this element is valid. If empty, the element is not restricted to any specific surfaces.",
    "m_AllowedSurfaceProperties": "List of surface properties on which this element is valid. If empty element is not restricted to any specific surfaces.",
    "m_Children": "List of the root level elements making up the smart prop definition, each element may be an entire tree.",
    "m_ChoiceSelection": "Specifies the index of the material group choice to pick",
    "m_Color": "Color to be applied if this choice is selected.",
    "m_ColorChoices": "List of possible colors which may be selected",
    "m_ColorPosition": "[ 0, 1 ] Value specifying the location on the gradient to pick the color from.",
    "m_ColorSelection": "Specifies the index of the color to pick",
    "m_CoordinateSpace": "Specifies the coordinate space of the specified position value.",
    "m_CoordinateSpaceA": "Specifies the coordinate space of position A.",
    "m_CoordinateSpaceB": "Specifies the coordinate space of position B.",
    "m_DefaultPath": "A set of points defining a path to use when an external path isn't specified. This will be used in the preview and thumbnail for the smart prop. It will also be used when the smart prop is placed in Hammer before a path is selected.",
    "m_DefaultPathInWorldSpace": "If enabled, the default path values will be treated as world space values, if disabled they are treated as object space values. Typically it makes sense for literal values to be treated as being in object space, but if the values are being supplied by locators they will typically be in world space.",
    "m_DefaultValue": "Default material group (skin) to assign to the variable value.",
    "m_DirectionSpace": "Specifies the coordinate space the trace direction vector is specified in.",
    "m_DirectionVector": "Specifies which direction vector to save.",
    "m_DisallowedMaterialAttributes": "List of material attributes on which this element is not valid. If empty, the element is not restricted to any specific surfaces.",
    "m_DisallowedSurfaceProperties": "List of surface properties on which this element is not valid. If empty element is not restricted to any specific surfaces.",
    "m_DisplayColor": "Color to display the rotator handle with.",
    "m_DisplayName": "Name of the parameter which will appear as a property in the Hammer object properties ui when selecting an object using this smart prop.",
    "m_DistributionMode": "Specifies the method to be used to distribute.",
    "m_EndPointA": "End point of the line to trace to.",
    "m_EndPointB": "End point of the line to trace to.",
    "m_EndPointSpaceA": "Coordinate space the end point is specified in.",
    "m_EndPointSpaceB": "Coordinate space the end point is specified in.",
    "m_Expression": "Stop placing copies of the children when this expression evaluates to true.",
    "m_ForwardDirectionSpace": "Specifies the coordinate space the forward direction is being specified in",
    "m_Gradient": "Defines a color gradient from which a color can be selected based on the selection mode.",
    "m_GridArrangement": "ARRAY: Grid is a specific number of grid divisions. FILL: The boundary is filled with as many as will fit at the specified cell spacing.",
    "m_GridOriginMode": "Specifies the overall grid origin location. Corner origin grids default to quadrant I, but may be expressed in others using negative values for Width and/or Length.",
    "m_HandleColor": "Color to use to display the configuration handle.",
    "m_HandleShape": "Shape of the configuration handle to display.",
    "m_HandleSize": "Size of the configuration handle.",
    "m_HideExpression": "Expression to evaluate to determine if this parameter should be hidden. Can be used to hide this parameter based on the state of other parameters.",
    "m_LocatorName": "Name of the locator. This can be used to reference the locator in this element or its children. If the locator is configurable, the locator will be identified by this name in Hammer.",
    "m_Material": "Material to which color tint is to be applied.",
    "m_MaterialGroupName": "Specifies the name of the material group (skin) to use when displaying the specified model.",
    "m_MaterialReplacements": "Table specifying pairs of existing materials and the material to replace them with.",
    "m_Mode": "Specifies how the selected color should be applied to the current color.",
    "m_Name": "Name used to identify the rotator. Must be unique within the parent element.",
    "m_Origin": "Specifies the origin point for the start of the trace. To trace from the current position, set to < 0, 0, 0 > and set the coordinate space to Element Space",
    "m_OriginSpace": "Coordinate space the origin is specified in. Using Element space allows specifying a value relative to the current position. However, world space should generally be used when for variable values.",
    "m_OriginalMaterial": "Original material to replace. This is the material specified in the model, including any material group asignment within the model. Does not consider any existing material overrides specified within the smart prop.",
    "m_OutputChoiceVariableName": "If a variable name is specified, sets the value of that variable to the index of the selected choice",
    "m_OutputCoordinateSpace": "Specifies the coordinate space the distance should be computed in. The scale of the coordinate space may affect the distance value.",
    "m_OutputVariable": "Specifies a float variable to which the rotation value should be output. The variable only receives the rotation around the axis, the axis of rotation does not affect this output.",
    "m_PathName": "Name of the path to use. This path name will show up in the property editor when selecting a placement of this smart prop in Hammer, allowing selection of a path object in the map to use.",
    "m_PathSpace": "Specifies the space in which the provided input path is to be evalauted.<br><br><b>World Space</b>: The input path will be evaluated in world space, such that child elements will be placed directly on the target path regardless of the transform of the smart prop object. <br><b>Object Space</b>: The world space transform of the input path will be ignored and instead the path will be evaluated relative to the transform of the smart prop object. <br><b>Element Space</b>: The world space transform of the input path will be ignored and instead the path will be evaluated relative to the transform of the current element within the smart prop.",
    "m_PlaceAtPositions": "Specifies the method to use to determine which positions this element should be placed at along the path.",
    "m_PlacementMode": "Specifies how the positions are computed based on the radius.",
    "m_PointSpace": "Specifies the coordinate space in which the end point values are specified.",
    "m_ReadOnlyExpression": "Expression to evaluate to detemrine if this parameter should be read-only. Can be used to make this parameter read-only based on the state of other parameters.",
    "m_ReplacementMaterial": "New material to replace the original material with.",
    "m_SelectionMode": "Specifies how the material group is to be selected from the authored set of choices",
    "m_SpecificChildIndex": "Specifies the index of the child to pick.",
    "m_StateName": "Name to assign to the saved state, the save state can be restored later using this name.",
    "m_SurfacePropertyOverride": "If non-empty, specifies the name of a surface property to use for all physics shapes of the specified model, overriding any surface properties specified within the model.",
    "m_TargetPoint": "The target point to trace to from the origin.",
    "m_TargetPointSpace": "Specifies the coordinate space the target point is specified in.",
    "m_TargetSpace": "Space in which the target position is defined.",
    "m_UpDirectionSpace": "Specifies the coordinate space the up direction is being specified in",
    "m_UpSpace": "Space in which the up target is defined.",
    "m_VariableName": "Material group variable to set to the selected choice.",
    "m_bAlignOrientation": "Align the initial orientation of each placed object based on it position on the sphere or circle.",
    "m_bAllowAtEnd": "Should this element be placed at the last positions on the path",
    "m_bAllowAtStart": "Should this element be placed at the first positions on the path",
    "m_bAllowScale": "Controls whether or not the configuration of the locator can include scale. If enabled scale can be applied to the editable locator in Hammer. If disabled the scale will not be editable and the current scale will be used.",
    "m_bAlternateShift": "Shifts every other cell row and/or column.",
    "m_bApplyToCurrentTransform": "Should the rotation be applied to the current transform.",
    "m_bCastShadows": "Should the entity created by this element cast shadows.",
    "m_bClearCurrentOverrides": "If enabled, clear any previous material overrides, so that only the material replacements specified in this table will be active.",
    "m_bConfigurable": "Controls whether or not the locator can be edited in a smart prop configuration. If enabled an editable locator will appear when the smart prop is placed in Hammer. Any changes to that locator will modify the current transform.",
    "m_bContinuousSpline": "Enables an alternate interpolation method that doesnt deform endpoint tangents.",
    "m_bDeformationEnabled": "Should the deformation be applied. If disabled the children will still be placed, but will not be deformed. Esentially making the element behave as a group.",
    "m_bDetailObject": "If enabled the model will be rendered as a detail object, which is faster for placing many small objects and has fade out functionality, but may have different lighting characteristics. Detail object models support only uniform scale and will use the largest component of the scale value.",
    "m_bDisableDynamicDeformable": "If checked, this model will not deform in game when the smart prop is placed inside a dynamic deformable entity (such as func_deformable_brush).",
    "m_bDiscardIfUknown": "If true, the parent element will be discarded there is no state with the specified name. If false, and there is no state with the specified name then no changes are made.",
    "m_bDisplayModel": "If enabled a model will be displayed at the position of the sizer that can be used to select the sizer in Hammer.",
    "m_bEnd": "Is this an element which should be placed at the end of the line.",
    "m_bEnforceLimits": "If enabled, the minimum and maximum rotation angles will be used to limit the range of the rotation.",
    "m_bExposeAsParameter": "If enabled, this value will be exposed as a parameter that can be set on the smart prop object in hammer.",
    "m_bForceStatic": "Force this model to be placed as a static model rather then generating an entity.",
    "m_bIgnoreCables": "Do not trace against cable geometry.",
    "m_bIgnoreEntities": "Do not trace against dynamic entities which may move in game.",
    "m_bIgnoreModels": "Do not trace against any models (only hit world geometry).",
    "m_bIgnoreNoDraw": "Do not trace against no draw materials (material attribute 'mapbuilder.nodraw').",
    "m_bIgnoreObjectRotation": "If enabled, the rotation will be reset to a world space instead of object space, meaning any rotation applied to the object in Hammer will be ignored.",
    "m_bIgnoreObjectScale": "If enabled, the object level scale will be ignored, meaning any scale applied in Hammer will have no effect on the element or its children.",
    "m_bIgnoreSky": "Do not trace against sky materials (attribute 'mapbuilder.sky').",
    "m_bIgnoreToolMaterials": "Do not trace against tool materials (attribute 'tools.toolsmaterial').",
    "m_bIgnoreTranslucent": "Do not trace against translucent materials (materials with 'alphatest' or 'translucent' attributes).",
    "m_bInvert": "When true, we only consider closed edges (edges with exactly two neighboring faces).",
    "m_bLocalEvaluationState": "If enabled, any changes made to the evaluation state by the target smart prop (as well as modifiers) will only apply locally and will not affect the evaluation state of the parent. Disabling this will allow modifications to the evaluation state by the referenced smart prop to apply the current state of the of the parent. For example if the referenced smart prop applies a transform and you want the transform to affect the elements in the parent after this element, then you should disable local evaluation state.",
    "m_bNormalized": "Should the return value be normalized to unit length (direction vector).",
    "m_bOrientAlongLine": "Should the child elements be oriented based on the line. If enabled the child elements placed on the line will be oriented such that their +x axis points along the line towards the end point.",
    "m_bPlane": "Interpret Vector B as plane normal.",
    "m_bPrioritizeUp": "When the up direction is not orthogonal to the line direction normally the up vector will be adjusted to make it orthogonal to the line direction. If prioritize up is true, then the up direction will be maintained and the forward direction will be adjusted.",
    "m_bResetPitch": "Should the pitch (rotation around left vector) value be reset.",
    "m_bResetRoll": "Should the roll (rotation around forward vector) value be reset.",
    "m_bResetYaw": "Should the yaw (roation around the up vector) value be reset.",
    "m_bRigidDeformation": "If enabled, only the transform of the model will be modified by any active deformer, the vertices of the model will not be changed by the deformer.",
    "m_bSharedVert": "When true, only consider open/closed edges that share a vert with another open/closed edge.",
    "m_bStart": "Is this an element which should be placed at the start of the line.",
    "m_bStartAsleep": "Should this physics prop start in a sleeping (non-simulating) state such that it won't update until it is woken up by an external event.",
    "m_bTraceAway": "If enabled, instead of tracing from the origin to the target point, trace away from the target point for the specified distance starting at the origin.",
    "m_bUseFixedUpDirection": "If true, treat the specified up direction as fixed up direction to apply to all elements placed on the path. If false the up direction is just an initial direction.",
    "m_bUseProjectedDistance": "Compute the spacing distance in the 2d plane defined by the up direction. Most useful when using a fixed up direction, if maintaining a distance in the 2d plane is more important than maintaing distance along the path.",
    "m_bVerticalLength": "Layout length vertically (Along Z axis instead of Y).",
    "m_fFalloff": "Adjust deformation falloff from the center of the region to the endpoints.",
    "m_fRadius": "The distance from the line formed by the endpoints that encapsulated the deformation region.",
    "m_flAlternateShiftLength": "Vary cell shift in Y.",
    "m_flAlternateShiftWidth": "Vary cell shift in X.",
    "m_flBendAngle": "Bend amount to apply, specified in degrees. Bend occurs along the local x-axis and bends around the local z-axis",
    "m_flBendPoint": "[ 0, 1 ] Value specifying the location along the local x-axis the bend will occur around",
    "m_flBendRadius": "Radius of the bend. If 0 the radius will be computed automatically to preserve the length of the inner edge of the x-axis. If a non-zero value is specified then the inner edge will maintain this radius, but its length will change.",
    "m_flDisplayRadius": "Radius at which the rotator handle should be displayed.",
    "m_flDisplayScale": "Scale to apply only to the locator model",
    "m_flInitialAngle": "Specifies the angle the rotator should be set to initially.",
    "m_flLength": "Specifies the length of the line that will be taken up if this element is selected.",
    "m_flMaxAngle": "Specifies the minimum angle limit in degrees",
    "m_flMaxLength": "Maximum allowable length for the object. Must be >= length. If length is 100 and maximum length is 160, then the object may be assigned a scale in the rage [ 1.0, 1.6 ].",
    "m_flMinAngle": "Specifies the minimum angle limit in degrees",
    "m_flMinLength": "Minimum allowable length for the object. Must be <= length. If length is 100 and minimum length is 20, then the object may be assigned a scale in the rage [ 0.2, 1.0 ].",
    "m_flOffsetAlongPath": "Offset from the start of the path to place the first point.",
    "m_flOriginOffset": "Offset to apply to the specified origin along the trace direction to compute the starting point of the trace.",
    "m_flPositionRadiusInner": "Inner radius from the placement position where the model can appear.",
    "m_flPositionRadiusOuter": "Outer radius from the placement position where the model can appear.",
    "m_flProbability": "0.0 to 1.0 value indicating the probability of this element being evaluated. Where a value of 0 means the element will never be evaluated and 1.0 means it will always be evaluated",
    "m_flRandomScaleMax": "Maximum scale range",
    "m_flRandomScaleMin": "Minimum scale range",
    "m_flRandomness": "0 to 1 value indicating the amout of random offset that should be applied to the reguluarly spaced positions",
    "m_flScale": "Scale to apply to the current transform",
    "m_flSnapIncrement": "If non-zero, specifies the increment to which the randomly selected scale value will be snapped. Note that the snap value is absolute, not relative to the min or max, but if the min or max are not multiples of the snap value they can still be selected.",
    "m_flSnappingIncrement": "Specifies the number of degrees the rotation should snap to. If set to 0, then the rotation snapping will be controlled by the rotation snapping in Hammer.",
    "m_flSpacing": "Spacing between points on the path",
    "m_flSpacingLength": "Minimum Length of filled grid cells.",
    "m_flSpacingWidth": "Minimum Width of filled grid cells.",
    "m_flSurfaceSlopeMax": "Maximum slope on which the target will be placed.",
    "m_flSurfaceSlopeMin": "Minimum slope on which the target will be placed. Slope is a [ 0, 180 ] value of the surface normal rotation from up such that 0 is a horizontal surface (floor), 90 is a vertical surface (wall), 180 is horizontal upside down surface (ceiling).",
    "m_flSurfaceUpInfluence": "How much should the surface normal up direction influence the final orientation. [ 0, 1 ] where 0 = don't modify the orientation, 1 = completely re-orient to match the surface.",
    "m_flTraceLength": "Maximum length of the trace. Surfaces beyond this distance will not be hit.",
    "m_flUniformModelScale": "Uniform scale to be applied to the model, certain properties like detail object mean only uniform scale may be applied to the model.",
    "m_flWeight": "Relative weight of this choice, higher weighted choices are more likely to be selected.",
    "m_flWidth": "Overall grid dimension along X axis.",
    "m_hSmartProp": "Name of the target smart prop resource (.vsmart) to evaluate.",
    "m_material": "Target material name.",
    "m_nContentVersion": "Specifies the current version of this smart prop. Any existing references to this smart prop with an older version number will not automatically update.",
    "m_nCount": "Number of instances of this object and its children to be placed.",
    "m_nCountL": "Grid segments along Length axis.",
    "m_nCountMax": "Maximum number of instances of this object and its children to be placed.",
    "m_nCountMin": "Minimum number of instances of this object and its children to be placed.",
    "m_nCountW": "Grid segments along width axis.",
    "m_nDeformableAttachmentMode": "If the smart prop is child of a deformable entity, this setting specifies how the entity generated by this element will be attached to the deformable surface.",
    "m_nDeformableOrientationMode": "If the smart prop is child of a deformable entity, this setting specifies how the entity generated by this element will be oriented relative to the deformable surface.",
    "m_nDetailObjectFadeLevel": "Controls the size at which a model marked as a detail object will fade out.",
    "m_nLodLevel": "Select model LOD level. The default Auto LOD means the lod will be picked based on the size of the model on screen. If a specific level is selected, then that lod level will always be used regardless of the size of the model on screen.",
    "m_nMaxDepth": "Maximum depth of smart prop evaluation stack during evaluation.",
    "m_nNoHitResult": "Specifies the behavior when the trace does not hit a surface.",
    "m_nNthPositionIndexOffset": "Specifies an offset to use when determining the Nth position to place an element at. For example if placing at every third position with an offset of 0, an element will appear at positions 1, 4, 7, and so on. But if an offset of 2 is set instead of 0, then an element will appear at positions 3, 6, and 9 and so on.",
    "m_nPickMode": "Specifies how scale is applied to each of the selected element in order to fit them to the line.",
    "m_nPlaceEveryNthPosition": "Specifies the spacing between positions. For example, a value of 1 will place the element at very position, 2 every other position, 3 every third position",
    "m_nReferenceID": "This property can be used only in Hammer5Tools for elements. This property is used to copy modifiers and properties from the selected element, respecting overrides. Important: it cannot be visible in the viewport — you have to save the file.",
    "m_nScaleMode": "Specifies how scale is applied to each of the selected element in order to fit them to the line.",
    "m_nTargetOpenEdgeCount": "Iterate through faces with 'n' open edges (edges with only one neighboring face).",
    "m_nTargetVertexCount": "Iterate through faces with target vertex count.",
    "m_sModelName": "Model containing the set of material groups to select.",
    "m_sSmartProp": "Name of the target smart prop resource (.vsmart) to evaluate.",
    "m_vAlignDirection": "Vector in the local space of the child element to be aligned with sphere or circle",
    "m_vAngles": "A local rotation to apply to apply the base volume of the deformer that will not apply to its children. This can be used to alter the direction of the deformation.",
    "m_vEnd": "Specifies the end point of the line in the specified coordinate space.",
    "m_vHandleOffset": "Specifies an offset in the local space of the element to apply to the configuration handle.",
    "m_vModelScale": "Scale factor (may be non-uniform) to be applied directly to the model (in the model's local space).",
    "m_vOffset": "Offset of the rotator relative to the current transform. This allows the rotator to be created at an offset location without applying that offset to the current transform.",
    "m_vOrigin": "A local offset to apply to the base volume of the deformer that will not apply to its children.",
    "m_vOriginPos": "Position of origin point.",
    "m_vPathOffset": "Offset to apply to the path, specifies a horizontal and vertical offset to apply relative to the up direction.",
    "m_vPlaneUpDirection": "Vector up direction of the plane of the circle. This in the local space of the current element.",
    "m_vPosition": "Local space position translation to apply to the current transform",
    "m_vRandomPositionMax": "Maximum random position offset",
    "m_vRandomPositionMin": "Minimum random position offset",
    "m_vRandomRotationMax": "Maximum rotation range",
    "m_vRandomRotationMin": "Minimum rotation range",
    "m_vRotation": "Local space rotation (in degrees) to apply to the current transform",
    "m_vRotationAxis": "Axis around which the rotation will occur",
    "m_vScale": "Scale the center of the deformation region.",
    "m_vSize": "Size of the base volume to be deformed.",
    "m_vSnapIncrement": "If non-zero, specifies the increment to which the randomly selected offset value will be snapped. Note that the snap value is absolute, not relative to the min or max, but if the if the min or max are not multiples of the snap value they can still be selected.",
    "m_vStart": "Specifies the start point of the line in the specified coordinate space.",
    "m_vTargetPos": "position of target point.",
    "m_vUpDirection": "If not using a fixed up direction, provides an initial up direction which will be used to determine the orientation of first element on the path, after that the elements will incrementally update to follow the path and may not match this direction. If Use Fixed Up direction is specified, then all elements will use this direction to deterime their up direction.",
    "m_vUpPos": "position of up point.",
    "CSmartPropElement_BendDeformer": "Creates a bend deformer that is applied to child elements. The deformation bends the local space x-axis around the local space z-axis. The Angles property can be used to rotate the local axis to change the direction of deformation.",
    "BendDeformer": "Creates a bend deformer that is applied to child elements. The deformation bends the local space x-axis around the local space z-axis. The Angles property can be used to rotate the local axis to change the direction of deformation.",
    "Element_BendDeformer": "Creates a bend deformer that is applied to child elements. The deformation bends the local space x-axis around the local space z-axis. The Angles property can be used to rotate the local axis to change the direction of deformation.",
    "CSmartPropElement_FitOnLine": {
        "description": "An element which fits one or more instances of a set of choices on to a line.",
        "image": r"images/help/fitonline.png",
    },
    "FitOnLine": {
        "description": "An element which fits one or more instances of a set of choices on to a line.",
        "image": r"images/help/fitonline.png",
    },
    "Element_FitOnLine": {
        "description": "An element which fits one or more instances of a set of choices on to a line.",
        "image": r"images/help/fitonline.png",
    },
    "Fit On Line": {
        "description": "An element which fits one or more instances of a set of choices on to a line.",
        "image": r"images/help/fitonline.png",
    },
    "fitonline": {
        "description": "An element which fits one or more instances of a set of choices on to a line.",
        "image": r"images/help/fitonline.png",
    },
    "CSmartPropElement_Group": {
        "description": "A group of elements that will all be evaulated.",
        "image": r"images/help/group.jpg",
    },
    "Group": {
        "description": "A group of elements that will all be evaulated.",
        "image": r"images/help/group.jpg",
    },
    "Element_Group": {
        "description": "A group of elements that will all be evaulated.",
        "image": r"images/help/group.jpg",
    },
    "CSmartPropElement_Layout2DGrid": "Generates set of child instances arranged in a regular grid layout.",
    "Layout2DGrid": "Generates set of child instances arranged in a regular grid layout.",
    "Element_Layout2DGrid": "Generates set of child instances arranged in a regular grid layout.",
    "CSmartPropElement_MidpointDeformer": "Soft deform the center of a volume defined by two endpoints.",
    "MidpointDeformer": "Soft deform the center of a volume defined by two endpoints.",
    "Element_MidpointDeformer": "Soft deform the center of a volume defined by two endpoints.",
    "CSmartPropElement_Model": {
        "description": "Places a model as the child of an element.",
        "image": r"images/help/img_placeholder.png",
    },
    "Model": {
        "description": "Places a model as the child of an element.",
        "image": r"images/help/img_placeholder.png",
    },
    "Element_Model": {
        "description": "Places a model as the child of an element.",
        "image": r"images/help/img_placeholder.png",
    },
    "CSmartPropElement_ModifyState": "An element which is used to apply a set of modifiers to the state of its parent.",
    "ModifyState": "An element which is used to apply a set of modifiers to the state of its parent.",
    "Element_ModifyState": "An element which is used to apply a set of modifiers to the state of its parent.",
    "Modify State": "An element which is used to apply a set of modifiers to the state of its parent.",
    "CSmartPropElement_PickOne": {
        "description": "An element which selects a single choice from its set of child choices.",
        "image": r"images/help/pick_one.jpg",
    },
    "PickOne": {
        "description": "An element which selects a single choice from its set of child choices.",
        "image": r"images/help/pick_one.jpg",
    },
    "Element_PickOne": {
        "description": "An element which selects a single choice from its set of child choices.",
        "image": r"images/help/pick_one.jpg",
    },
    "Pick One": {
        "description": "An element which selects a single choice from its set of child choices.",
        "image": r"images/help/pick_one.jpg",
    },
    "CSmartPropElement_PlaceInSphere": "An element which places multiple instances of its child elements within a radius.",
    "PlaceInSphere": "An element which places multiple instances of its child elements within a radius.",
    "Element_PlaceInSphere": "An element which places multiple instances of its child elements within a radius.",
    "CSmartPropElement_PlaceMultiple": {
        "description": "An element which places multiple instances of its child elements.",
        "image": r"images/help/place_multiple.jpg",
    },
    "PlaceMultiple": {
        "description": "An element which places multiple instances of its child elements.",
        "image": r"images/help/place_multiple.jpg",
    },
    "Element_PlaceMultiple": {
        "description": "An element which places multiple instances of its child elements.",
        "image": r"images/help/place_multiple.jpg",
    },
    "Place Multiple": {
        "description": "An element which places multiple instances of its child elements.",
        "image": r"images/help/place_multiple.jpg",
    },
    "CSmartPropElement_PlaceOnMesh": "Place Children on Mesh Components.",
    "PlaceOnMesh": "Place Children on Mesh Components.",
    "Element_PlaceOnMesh": "Place Children on Mesh Components.",
    "CSmartPropElement_PlaceOnPath": {
        "description": "An element which places an instance of its child elements at a specified interval along a path.",
        "image": r"images/help/place_on_path.png",
    },
    "PlaceOnPath": {
        "description": "An element which places an instance of its child elements at a specified interval along a path.",
        "image": r"images/help/place_on_path.png",
    },
    "Element_PlaceOnPath": {
        "description": "An element which places an instance of its child elements at a specified interval along a path.",
        "image": r"images/help/place_on_path.png",
    },
    "Place On Path": {
        "description": "An element which places an instance of its child elements at a specified interval along a path.",
        "image": r"images/help/place_on_path.png",
    },
    "CSmartPropElement_PropDynamic": "Places a prop dynamic entity.",
    "PropDynamic": "Places a prop dynamic entity.",
    "Element_PropDynamic": "Places a prop dynamic entity.",
    "Prop Dynamic": "Places a prop dynamic entity.",
    "CSmartPropElement_PropPhysics": {
        "description": "Places a prop physics entity.",
        "image": r"images/help/prop_physics.png",
    },
    "PropPhysics": {
        "description": "Places a prop physics entity.",
        "image": r"images/help/prop_physics.png",
    },
    "Element_PropPhysics": {
        "description": "Places a prop physics entity.",
        "image": r"images/help/prop_physics.png",
    },
    "Prop Physics": {
        "description": "Places a prop physics entity.",
        "image": r"images/help/prop_physics.png",
    },
    "CSmartPropElement_SmartProp": "Evaluates a specified smart prop as a child of the current element.",
    "SmartProp": "Evaluates a specified smart prop as a child of the current element.",
    "Element_SmartProp": "Evaluates a specified smart prop as a child of the current element.",
    "CSmartPropFilter_Expression": "Evaluates the specified expression, if the result of the expression is false evaluation of the element is stopped.",
    "Expression": "Evaluates the specified expression, if the result of the expression is false evaluation of the element is stopped.",
    "Filter_Expression": "Evaluates the specified expression, if the result of the expression is false evaluation of the element is stopped.",
    "CSmartPropFilter_MaterialAttributes": "Allows the parent element to be conditionally evaluated based on attributes assigned to the surface material.",
    "MaterialAttributes": "Allows the parent element to be conditionally evaluated based on attributes assigned to the surface material.",
    "Filter_MaterialAttributes": "Allows the parent element to be conditionally evaluated based on attributes assigned to the surface material.",
    "CSmartPropFilter_Probability": "Causes the parent element to only be evaluated with a specified random probability.",
    "Probability": "Causes the parent element to only be evaluated with a specified random probability.",
    "Filter_Probability": "Causes the parent element to only be evaluated with a specified random probability.",
    "CSmartPropFilter_SurfaceAngle": "Allows the parent element to be conditionally evaluated base on the current surface angle. The surface angle is set based on the initial placement of the smart prop object, but can also be updated by the Trace to Surface modifier.",
    "SurfaceAngle": "Allows the parent element to be conditionally evaluated base on the current surface angle. The surface angle is set based on the initial placement of the smart prop object, but can also be updated by the Trace to Surface modifier.",
    "Filter_SurfaceAngle": "Allows the parent element to be conditionally evaluated base on the current surface angle. The surface angle is set based on the initial placement of the smart prop object, but can also be updated by the Trace to Surface modifier.",
    "CSmartPropFilter_SurfaceProperties": "Allows the parent element to be conditionally evaluated based on surface properties.",
    "SurfaceProperties": "Allows the parent element to be conditionally evaluated based on surface properties.",
    "Filter_SurfaceProperties": "Allows the parent element to be conditionally evaluated based on surface properties.",
    "CSmartPropFilter_VariableValue": "Compares the current value of a variable to the specified value. If the comparison is false the element evaluation is stopped.",
    "VariableValue": "Compares the current value of a variable to the specified value. If the comparison is false the element evaluation is stopped.",
    "Filter_VariableValue": "Compares the current value of a variable to the specified value. If the comparison is false the element evaluation is stopped.",
    "CSmartPropOperation_ComputeCrossProduct3D": "Compute a dot or cross product between two 3D vectors",
    "ComputeCrossProduct3D": "Compute a dot or cross product between two 3D vectors",
    "Operation_ComputeCrossProduct3D": "Compute a dot or cross product between two 3D vectors",
    "CSmartPropOperation_ComputeDistance3D": "Compute the distance between two 3D points",
    "ComputeDistance3D": "Compute the distance between two 3D points",
    "Operation_ComputeDistance3D": "Compute the distance between two 3D points",
    "CSmartPropOperation_ComputeDotProduct3D": "Compute a dot or cross product between two 3D vectors",
    "ComputeDotProduct3D": "Compute a dot or cross product between two 3D vectors",
    "Operation_ComputeDotProduct3D": "Compute a dot or cross product between two 3D vectors",
    "CSmartPropOperation_ComputeNormalizedVector3D": "Normalize the value of a 3d vector.",
    "ComputeNormalizedVector3D": "Normalize the value of a 3d vector.",
    "Operation_ComputeNormalizedVector3D": "Normalize the value of a 3d vector.",
    "CSmartPropOperation_ComputeProjectVector3D": "Project Vector A onto Vector B",
    "ComputeProjectVector3D": "Project Vector A onto Vector B",
    "Operation_ComputeProjectVector3D": "Project Vector A onto Vector B",
    "CSmartPropOperation_ComputeVectorBetweenPoints3D": "Compute the vector between two 3D points",
    "ComputeVectorBetweenPoints3D": "Compute the vector between two 3D points",
    "Operation_ComputeVectorBetweenPoints3D": "Compute the vector between two 3D points",
    "CSmartPropOperation_CreateLocator": "Create a locator with the current transform. The locator may optionally be configurable, so that its transform can be modified in Hammer.",
    "CreateLocator": "Create a locator with the current transform. The locator may optionally be configurable, so that its transform can be modified in Hammer.",
    "Operation_CreateLocator": "Create a locator with the current transform. The locator may optionally be configurable, so that its transform can be modified in Hammer.",
    "CSmartPropOperation_CreateRotator": "Create a rotator that will be displayed at the current location, allowing the user to manipulate a rotation around an axis. The rotation value can be applied to the current transform as well as saved to a variable.",
    "CreateRotator": "Create a rotator that will be displayed at the current location, allowing the user to manipulate a rotation around an axis. The rotation value can be applied to the current transform as well as saved to a variable.",
    "Operation_CreateRotator": "Create a rotator that will be displayed at the current location, allowing the user to manipulate a rotation around an axis. The rotation value can be applied to the current transform as well as saved to a variable.",
    "CSmartPropOperation_CreateSizer": {
        "description": "Create a sizer that will be displayed at the current location, allowing the user to manipulate the specified set of size values.",
        "image": r"images/help/create_sizer.png",
    },
    "CreateSizer": {
        "description": "Create a sizer that will be displayed at the current location, allowing the user to manipulate the specified set of size values.",
        "image": r"images/help/create_sizer.png",
    },
    "Operation_CreateSizer": {
        "description": "Create a sizer that will be displayed at the current location, allowing the user to manipulate the specified set of size values.",
        "image": r"images/help/create_sizer.png",
    },
    "Create Sizer": {
        "description": "Create a sizer that will be displayed at the current location, allowing the user to manipulate the specified set of size values.",
        "image": r"images/help/create_sizer.png",
    },
    "CSmartPropOperation_MaterialOverride": "Specifies a table of material replacements to apply to all following models. Mapping goes from the material specified by the model (including material group selection) to the replacement material. Previous material overrides are not considered when determining the base material.",
    "MaterialOverride": "Specifies a table of material replacements to apply to all following models. Mapping goes from the material specified by the model (including material group selection) to the replacement material. Previous material overrides are not considered when determining the base material.",
    "Operation_MaterialOverride": "Specifies a table of material replacements to apply to all following models. Mapping goes from the material specified by the model (including material group selection) to the replacement material. Previous material overrides are not considered when determining the base material.",
    "CSmartPropOperation_MaterialTint": "Set a color tint to apply to a specific material.",
    "MaterialTint": "Set a color tint to apply to a specific material.",
    "Operation_MaterialTint": "Set a color tint to apply to a specific material.",
    "CSmartPropOperation_RandomColorTintColor": "Set the color tint to a selection from within the defined gradient.",
    "RandomColorTintColor": "Set the color tint to a selection from within the defined gradient.",
    "Operation_RandomColorTintColor": "Set the color tint to a selection from within the defined gradient.",
    "CSmartPropOperation_RandomOffset": "Apply a random position offset to the current transform.",
    "RandomOffset": "Apply a random position offset to the current transform.",
    "Operation_RandomOffset": "Apply a random position offset to the current transform.",
    "CSmartPropOperation_RandomRotation": "Apply a random rotation to the current transform.",
    "RandomRotation": "Apply a random rotation to the current transform.",
    "Operation_RandomRotation": "Apply a random rotation to the current transform.",
    "CSmartPropOperation_RandomScale": "Apply a random scale to the current transform.",
    "RandomScale": "Apply a random scale to the current transform.",
    "Operation_RandomScale": "Apply a random scale to the current transform.",
    "CSmartPropOperation_ResetRotation": "Reset the current rotation such the element only inherits the object level rotation, but does not inherit the rotation applied to its parent.",
    "ResetRotation": "Reset the current rotation such the element only inherits the object level rotation, but does not inherit the rotation applied to its parent.",
    "Operation_ResetRotation": "Reset the current rotation such the element only inherits the object level rotation, but does not inherit the rotation applied to its parent.",
    "CSmartPropOperation_ResetScale": "Reset the current scale such the element only inherits the object level scale, but does not inherit the scale applied to its parent.",
    "ResetScale": "Reset the current scale such the element only inherits the object level scale, but does not inherit the scale applied to its parent.",
    "Operation_ResetScale": "Reset the current scale such the element only inherits the object level scale, but does not inherit the scale applied to its parent.",
    "CSmartPropOperation_RestoreState": "Replace the current state with a previously saved state.",
    "RestoreState": "Replace the current state with a previously saved state.",
    "Operation_RestoreState": "Replace the current state with a previously saved state.",
    "CSmartPropOperation_RigidDeformation": "Apply the active deformer to the current transform as a rigid deformation and disable the deformer.",
    "RigidDeformation": "Apply the active deformer to the current transform as a rigid deformation and disable the deformer.",
    "Operation_RigidDeformation": "Apply the active deformer to the current transform as a rigid deformation and disable the deformer.",
    "CSmartPropOperation_Rotate": "Apply a rotation to the current transform.",
    "Rotate": "Apply a rotation to the current transform.",
    "Operation_Rotate": "Apply a rotation to the current transform.",
    "CSmartPropOperation_RotateTowards": "Apply a rotation to the current transform according to the alignment of two points.",
    "RotateTowards": "Apply a rotation to the current transform according to the alignment of two points.",
    "Operation_RotateTowards": "Apply a rotation to the current transform according to the alignment of two points.",
    "CSmartPropOperation_SaveColor": "Save the current color tint value to a specified variable",
    "SaveColor": "Save the current color tint value to a specified variable",
    "Operation_SaveColor": "Save the current color tint value to a specified variable",
    "CSmartPropOperation_SaveDirection": "Save the specified direction vector to a specified variable, in the requested coordinate space",
    "SaveDirection": "Save the specified direction vector to a specified variable, in the requested coordinate space",
    "Operation_SaveDirection": "Save the specified direction vector to a specified variable, in the requested coordinate space",
    "CSmartPropOperation_SavePosition": "Save the current position to a specified variable in the requested coordinate space",
    "SavePosition": "Save the current position to a specified variable in the requested coordinate space",
    "Operation_SavePosition": "Save the current position to a specified variable in the requested coordinate space",
    "CSmartPropOperation_SaveScale": "Save the current scale factor to a specified variable.",
    "SaveScale": "Save the current scale factor to a specified variable.",
    "Operation_SaveScale": "Save the current scale factor to a specified variable.",
    "CSmartPropOperation_SaveState": "Save the current state, allowing it to be restored at a later state.",
    "SaveState": "Save the current state, allowing it to be restored at a later state.",
    "Operation_SaveState": "Save the current state, allowing it to be restored at a later state.",
    "CSmartPropOperation_SaveSurfaceNormal": "Save the current surface normal to a specified variable in the requested coordinate space",
    "SaveSurfaceNormal": "Save the current surface normal to a specified variable in the requested coordinate space",
    "Operation_SaveSurfaceNormal": "Save the current surface normal to a specified variable in the requested coordinate space",
    "CSmartPropOperation_Scale": "Apply a scale to the current transform.",
    "Scale": "Apply a scale to the current transform.",
    "Operation_Scale": "Apply a scale to the current transform.",
    "CSmartPropOperation_SetMateraialGroupChoice": "Picks a material group from a set of choices and assigns that material group to a specified variable.",
    "SetMateraialGroupChoice": "Picks a material group from a set of choices and assigns that material group to a specified variable.",
    "Operation_SetMateraialGroupChoice": "Picks a material group from a set of choices and assigns that material group to a specified variable.",
    "CSmartPropOperation_SetMaterialGroupChoice": "Picks a material group from a set of choices and assigns that material group to a specified variable.",
    "SetMaterialGroupChoice": "Picks a material group from a set of choices and assigns that material group to a specified variable.",
    "Operation_SetMaterialGroupChoice": "Picks a material group from a set of choices and assigns that material group to a specified variable.",
    "CSmartPropOperation_SetOrientation": "Set the current orientation from a specified forward and up vector.",
    "SetOrientation": "Set the current orientation from a specified forward and up vector.",
    "Operation_SetOrientation": "Set the current orientation from a specified forward and up vector.",
    "CSmartPropOperation_SetPosition": "Set the position of the current transform.",
    "SetPosition": "Set the position of the current transform.",
    "Operation_SetPosition": "Set the position of the current transform.",
    "CSmartPropOperation_SetTintColor": "Set the color tint to one color out of a pre-selected set of colors.",
    "SetTintColor": "Set the color tint to one color out of a pre-selected set of colors.",
    "Operation_SetTintColor": "Set the color tint to one color out of a pre-selected set of colors.",
    "CSmartPropOperation_SetVariable": "Set the value of a variable.",
    "SetVariable": "Set the value of a variable.",
    "Operation_SetVariable": "Set the value of a variable.",
    "CSmartPropOperation_TraceInDirection": "Perform a trace in a direction from a specified origin and stop when a surface is hit.",
    "TraceInDirection": "Perform a trace in a direction from a specified origin and stop when a surface is hit.",
    "Operation_TraceInDirection": "Perform a trace in a direction from a specified origin and stop when a surface is hit.",
    "CSmartPropOperation_TraceToLine": "Perform a trace from a specified origin point to a the closest point on a line.",
    "TraceToLine": "Perform a trace from a specified origin point to a the closest point on a line.",
    "Operation_TraceToLine": "Perform a trace from a specified origin point to a the closest point on a line.",
    "CSmartPropOperation_TraceToPoint": "Perform a trace between the specified origin and a specified target point.",
    "TraceToPoint": "Perform a trace between the specified origin and a specified target point.",
    "Operation_TraceToPoint": "Perform a trace between the specified origin and a specified target point.",
    "CSmartPropOperation_Translate": "Apply a position offset to the current transform.",
    "Translate": "Apply a position offset to the current transform.",
    "Operation_Translate": "Apply a position offset to the current transform.",
    "CSmartPropPulse_CreateLocator": "Create a locator with the current transform. The locator may optionally be configurable, so that its transform can be modified in Hammer.",
    "Pulse_CreateLocator": "Create a locator with the current transform. The locator may optionally be configurable, so that its transform can be modified in Hammer.",
    "CSmartPropPulse_CreateRotator": "Create a rotator that will be displayed at the current location, allowing the user to manipulate a rotation around an axis. The rotation value can be applied to the current transform as well as saved to a variable.",
    "Pulse_CreateRotator": "Create a rotator that will be displayed at the current location, allowing the user to manipulate a rotation around an axis. The rotation value can be applied to the current transform as well as saved to a variable.",
    "CSmartPropPulse_CreateSizer": {
        "description": "Create a sizer that will be displayed at the current location, allowing the user to manipulate the specified set of size values.",
        "image": r"images/help/create_sizer.png",
    },
    "Pulse_CreateSizer": {
        "description": "Create a sizer that will be displayed at the current location, allowing the user to manipulate the specified set of size values.",
        "image": r"images/help/create_sizer.png",
    },
    "CSmartPropPulse_FitOnLine": {
        "description": "An element which fits one or more instances of a set of choices on to a line.",
        "image": r"images/help/fitonline.png",
    },
    "Pulse_FitOnLine": {
        "description": "An element which fits one or more instances of a set of choices on to a line.",
        "image": r"images/help/fitonline.png",
    },
    "CSmartPropPulse_PickOneSelector": {
        "description": "An element which selects a single choice from its set of child choices.",
        "image": r"images/help/pick_one.jpg",
    },
    "PickOneSelector": {
        "description": "An element which selects a single choice from its set of child choices.",
        "image": r"images/help/pick_one.jpg",
    },
    "Pulse_PickOneSelector": {
        "description": "An element which selects a single choice from its set of child choices.",
        "image": r"images/help/pick_one.jpg",
    },
    "CSmartPropPulse_PlaceInSphere": "An element which places multiple instances of its child elements within a radius.",
    "Pulse_PlaceInSphere": "An element which places multiple instances of its child elements within a radius.",
    "CSmartPropPulse_SelectionChoiceWeight": "Specifies a weighting value which affects that likelyhood of selecting this element which picking a choice.",
    "SelectionChoiceWeight": "Specifies a weighting value which affects that likelyhood of selecting this element which picking a choice.",
    "Pulse_SelectionChoiceWeight": "Specifies a weighting value which affects that likelyhood of selecting this element which picking a choice.",
    "CSmartPropPulse_SelectionEndCap": "Specifies that this is a special part that should be used at the start or end of the line.",
    "SelectionEndCap": "Specifies that this is a special part that should be used at the start or end of the line.",
    "Pulse_SelectionEndCap": "Specifies that this is a special part that should be used at the start or end of the line.",
    "CSmartPropPulse_SelectionLinearLength": "Specifies the length of this element, used when fitting an element on to a line.",
    "SelectionLinearLength": "Specifies the length of this element, used when fitting an element on to a line.",
    "Pulse_SelectionLinearLength": "Specifies the length of this element, used when fitting an element on to a line.",
    "CSmartPropRoot": "Root of a smart prop, contains a list of elements to evaluate.",
    "Root": "Root of a smart prop, contains a list of elements to evaluate.",
    "CSmartPropSelectionCriteria_ChoiceWeight": "Specifies a weighting value which affects that likelyhood of selecting this element which picking a choice.",
    "ChoiceWeight": "Specifies a weighting value which affects that likelyhood of selecting this element which picking a choice.",
    "SelectionCriteria_ChoiceWeight": "Specifies a weighting value which affects that likelyhood of selecting this element which picking a choice.",
    "CSmartPropSelectionCriteria_EndCap": "Specifies that this is a special part that should be used at the start or end of the line.",
    "EndCap": "Specifies that this is a special part that should be used at the start or end of the line.",
    "SelectionCriteria_EndCap": "Specifies that this is a special part that should be used at the start or end of the line.",
    "CSmartPropSelectionCriteria_IsValid": "Specifies if this element is currently valid choice.",
    "IsValid": "Specifies if this element is currently valid choice.",
    "SelectionCriteria_IsValid": "Specifies if this element is currently valid choice.",
    "CSmartPropSelectionCriteria_LinearLength": "Specifies the length of this element, used when fitting an element on to a line.",
    "LinearLength": "Specifies the length of this element, used when fitting an element on to a line.",
    "SelectionCriteria_LinearLength": "Specifies the length of this element, used when fitting an element on to a line.",
    "CSmartPropSelectionCriteria_PathPosition": "Specifies the path positions at which this element may appear.",
    "PathPosition": "Specifies the path positions at which this element may appear.",
    "SelectionCriteria_PathPosition": "Specifies the path positions at which this element may appear.",
    "CSmartPropVariable_ApplyColorMode": "Specifies how a color tint value is to be applied with respect to the existing color tint",
    "ApplyColorMode": "Specifies how a color tint value is to be applied with respect to the existing color tint",
    "Variable_ApplyColorMode": "Specifies how a color tint value is to be applied with respect to the existing color tint",
    "CSmartPropVariable_ChoiceSelectionMode": "Specifies the method by which a child element is selected from a list.",
    "ChoiceSelectionMode": "Specifies the method by which a child element is selected from a list.",
    "Variable_ChoiceSelectionMode": "Specifies the method by which a child element is selected from a list.",
    "CSmartPropVariable_ColorSelectionMode": "Specifies the method by which a color selection is to be made.",
    "ColorSelectionMode": "Specifies the method by which a color selection is to be made.",
    "Variable_ColorSelectionMode": "Specifies the method by which a color selection is to be made.",
    "CSmartPropVariable_CoordinateSpace": "Specifies a coordinate space in which a point or vector value is defined.",
    "CoordinateSpace": "Specifies a coordinate space in which a point or vector value is defined.",
    "Variable_CoordinateSpace": "Specifies a coordinate space in which a point or vector value is defined.",
    "CSmartPropVariable_DirectionVector": "Specifies a basis direction vector ( Forward, Left, or UP).",
    "DirectionVector": "Specifies a basis direction vector ( Forward, Left, or UP).",
    "Variable_DirectionVector": "Specifies a basis direction vector ( Forward, Left, or UP).",
    "CSmartPropVariable_Direction": "Specifies a basis direction vector ( Forward, Left, or UP).",
    "Direction": "Specifies a basis direction vector ( Forward, Left, or UP).",
    "Variable_Direction": "Specifies a basis direction vector ( Forward, Left, or UP).",
    "CSmartPropVariable_DistributionMode": "Specifies a distribution mode used to determine how certain elements distribute instances of their children within a space.",
    "DistributionMode": "Specifies a distribution mode used to determine how certain elements distribute instances of their children within a space.",
    "Variable_DistributionMode": "Specifies a distribution mode used to determine how certain elements distribute instances of their children within a space.",
    "CSmartPropVariable_GridOriginMode": "Specifies where the origin of a child element is placed relative to each grid cell.",
    "GridOriginMode": "Specifies where the origin of a child element is placed relative to each grid cell.",
    "Variable_GridOriginMode": "Specifies where the origin of a child element is placed relative to each grid cell.",
    "CSmartPropVariable_GridPlacementMode": "Specifies how to place elements within a grid.",
    "GridPlacementMode": "Specifies how to place elements within a grid.",
    "Variable_GridPlacementMode": "Specifies how to place elements within a grid.",
    "CSmartPropVariable_Material": "Material Asset Variable",
    "Material": "Material Asset Variable",
    "Variable_Material": "Material Asset Variable",
    "CSmartPropVariable_Model": "Model Asset Variable",
    "Variable_Model": "Model Asset Variable",
    "CSmartPropVariable_OrientationMode": "Specifies how a fit on line element will pick which child elements it will place.",
    "OrientationMode": "Specifies how a fit on line element will pick which child elements it will place.",
    "Variable_OrientationMode": "Specifies how a fit on line element will pick which child elements it will place.",
    "CSmartPropVariable_PathPositions": "Specifies the set of positions that are valid for path placement.",
    "PathPositions": "Specifies the set of positions that are valid for path placement.",
    "Variable_PathPositions": "Specifies the set of positions that are valid for path placement.",
    "CSmartPropVariable_PickMode": "Specifies how a fit on line element will pick which child elements it will place.",
    "PickMode": "Specifies how a fit on line element will pick which child elements it will place.",
    "Variable_PickMode": "Specifies how a fit on line element will pick which child elements it will place.",
    "CSmartPropVariable_RadiusPlacementMode": "Specifies the shape (circle, or sphere) to use with elements that place children within a radius.",
    "RadiusPlacementMode": "Specifies the shape (circle, or sphere) to use with elements that place children within a radius.",
    "Variable_RadiusPlacementMode": "Specifies the shape (circle, or sphere) to use with elements that place children within a radius.",
    "CSmartPropVariable_ScaleMode": "Specifies how a fit on line element will scale generate scale values for the objects it places.",
    "ScaleMode": "Specifies how a fit on line element will scale generate scale values for the objects it places.",
    "Variable_ScaleMode": "Specifies how a fit on line element will scale generate scale values for the objects it places.",
    "CSmartPropVariable_SurfaceProperty": "Surface Property Variable",
    "SurfaceProperty": "Surface Property Variable",
    "Variable_SurfaceProperty": "Surface Property Variable",
    "CSmartPropVariable_TraceNoHit": "Specified what to do when a trace does not hit a surface.",
    "TraceNoHit": "Specified what to do when a trace does not hit a surface.",
    "Variable_TraceNoHit": "Specified what to do when a trace does not hit a surface.",
}


def resolve_image_path(path_str: str | None) -> str | None:
    """Resolve image path to an absolute path if it exists."""
    if not path_str:
        return None
    path_str = str(path_str).strip()
    if not path_str:
        return None
    if os.path.isabs(path_str) and os.path.exists(path_str):
        return path_str

    try:
        from gui.common import gui_assets_dir
        candidate1 = os.path.normpath(os.path.join(gui_assets_dir(), path_str))
        if os.path.exists(candidate1):
            return candidate1
    except Exception:
        pass

    return None


def get_tooltip_info(key: str, default_desc: str = "") -> tuple[str, str | None]:
    """Retrieve (description, image_path) for a given key from property_tooltips."""
    if not key:
        return default_desc, None

    keys_to_try = [key]
    if not key.startswith("m_"):
        keys_to_try.append(f"m_{key}")
    else:
        keys_to_try.append(key[2:])
        if len(key) > 4 and key[2] in "snbv" and key[3].isupper():
            keys_to_try.append(f"m_{key[3:]}")
            keys_to_try.append(key[3:])

    for k in keys_to_try:
        val = property_tooltips.get(k)
        if val is not None:
            if isinstance(val, dict):
                desc = val.get("description", default_desc)
                img = val.get("image")
                return desc, img
            return str(val), None

    return default_desc, None


def get_tooltip_info_multi(keys: list[str], default_desc: str = "") -> tuple[str, str | None]:
    """Try a sequence of keys until a match is found in property_tooltips."""
    for k in keys:
        if not k:
            continue
        desc, img = get_tooltip_info(k, "")
        if desc:
            return desc, img
    return default_desc, None
