soundevent_editor_properties = [
    # Float
    {'Volume': {'volume': 1}},
    {'Delay': {'delay': 1}},
    {'Pitch': {'pitch': 1}},
    {'Volume Random Min': {'volume_random_min': -0.5}},
    {'Volume Random Max': {'volume_random_max': 0.5}},
    {'Pitch Random Min': {'pitch_random_min': -0.5}},
    {'Pitch Random Max': {'pitch_random_max': -0.5}},
    {'Randomize Position Min Radius': {'randomize_position_min_radius': 2000}},
    {'Randomize Position Max Radius': {'randomize_position_max_radius': 3000}},
    {'Retrigger Interval Min': {'retrigger_interval_min': 10}},
    {'Retrigger Interval Max': {'retrigger_interval_max': 30}},
    {'Occlusion Intensity': {'occlusion_intensity': 0.0}},
    {'Distance Effect Mix': {'distance_effect_mix': 0.0}},
    {'Reverb Wet': {'reverb_wet': 1.0}},
    {'Occlusion Frequency Scale': {'occlusion_frequency_scale ': 1.0}},
    {'Vsnd Duration': {'vsnd_duration': 10}},
    {'Block Duration': {'block_duration': 0.0}},
    {'Block Distance': {'block_distance': 0.0}},
    {'Instance Limit': {'instance_limit': 0.0}},
    {'Reverb Source Wet': {'reverb_source_wet': 0.0}},
    {'Distance Multiplier': {'distance_multiplier': 1.5}},
    {'Broadcast Distance Override': {'broadcast_distance_override': 98.0}},
    {'Block Other Duration': {'block_other_duration': 0.3}},
    {'Block Other Distance': {'block_other_distance': 30.0}},
    {'Velocity Volume Seek Speed': {'velocity_volume_seek_speed': 700.0}},
    {'Ducking Bypass': {'ducking_bypass': 1.0}},
    {'Retrigger Radius': {'retrigger_radius': 10000.0}},
    {'Self Destruct Time': {'self_destruct_time': 20.0}},
    {'Value': {'value': 1.0}},
    {'Dsp Bypass': {'dsp_bypass': 0.0}},
    {'Occlusion Interval': {'occlusion_interval': 0.25}},
    {'Retrigger Count': {'retrigger_count': -1.0}},
    {'Dsp Blend': {'dsp_blend': 0.0}},
    {'Voice Culling Threshold': {'voice_culling_threshold': 0.01}},
    {'Volume Fade Out Input Max': {'volume_fade_out_input_max': 1.0}},
    {'Priority': {'priority': 2.0}},
    {'Volume Fade Initial Input Min': {'volume_fade_initial_input_min': 4.0}},
    {'Volume Fade Initial Input Max': {'volume_fade_initial_input_max': 12.0}},
    {'Volume Fade Initial Input Map Min': {'volume_fade_initial_input_map_min': 1.0}},
    {'Volume Fade Initial Input Map Max': {'volume_fade_initial_input_map_max': 0.5}},
    {'Startpoint 01': {'startpoint_01': 0.0}},
    {'Startpoint 02': {'startpoint_02': 0.0}},
    {'Startpoint 03': {'startpoint_03': 1.174}},
    {'Endpoint 01': {'endpoint_01': 53.992}},
    {'Endpoint 02': {'endpoint_02': 38.308}},
    {'Endpoint 03': {'endpoint_03': 55.851}},
    {'Sync Action To Startround': {'sync_action_to_startround': 1}},
    {'Stop At Time': {'stop_at_time': 10.0}},
    {'Restart Startpoint 01': {'restart_startpoint_01': 2.05}},
    {'Restart Startpoint 02': {'restart_startpoint_02': 2.05}},


    # Files
    {'Sound Files track': {'vsnd_files_track_01': []}},
    {'Vsnd Files': {'vsnd_files': 'sounds/music/survival_review_victory.vsnd'}},

    # Vector3
    {'Position': {'position': [0, 0, 0]}},
    {'Position Offset': {'position_offset': [0.0, 0.0, 20.0]}},

    # Bool
    {'Enable Child Events': {'enable_child_events': True}},
    {'Enable Retrigger': {'enable_retrigger': True}},
    {'Restrict Source Reverb': {'restrict_source_reverb': True}},
    {'Randomize Position Hemisphere': {'randomize_position_hemisphere': False}},
    {'Use Distance Unfiltered Stereo Mapping Curve': {'use_distance_unfiltered_stereo_mapping_curve': True}},
    {'Use Distance Volume Mapping Curve': {'use_distance_volume_mapping_curve': True}},
    {'Use Time Volume Mapping Curve': {'use_time_volume_mapping_curve': True}},
    {'Override Dsp Preset': {'override_dsp_preset': True}},
    {'Set Child Position': {'set_child_position': True}},
    {'Position Relative To Player': {'position_relative_to_player': False}},
    {'Use World Position': {'use_world_position': False}},
    {'Block Matching Events': {'block_matching_events': False}},
    {'Block Match Entity': {'block_match_entity': False}},
    {'Use Fadetime Volume Mapping Curve': {'use_fadetime_volume_mapping_curve': False}},
    {'Use Entity Position If Local Player': {'use_entity_position_if_local_player': True}},
    {'Display Broadcast': {'display_broadcast': True}},
    {'Use Baked Occlusion': {'use_baked_occlusion': True}},
    {'Preload Vsnds': {'preload_vsnds': True}},
    {'Use Impact Speed Input Volume Mapping Curve': {'use_impact_speed_input_volume_mapping_curve': True}},
    {'Set Mixlayer Amount Enable': {'set_mixlayer_amount_enable': True}},
    {'Block Other': {'block_other': True}},
    {'Use Velocity Volume Curve': {'use_velocity_volume_curve': True}},
    {'Use Velocity Eq': {'use_velocity_eq': True}},
    {'Use Volume Convar': {'use_volume_convar': True}},
    {'Stop Selection Music': {'stop_selection_music': 'true'}},
    {'Stop All Non Music': {'stop_all_non_music': 'true'}},
    {'Stop Music': {'stop_music': 'true'}},
    {'Vsnd Pause With Game': {'vsnd_pause_with_game': False}},
    {'Is Ui Sound': {'is_ui_sound': False}},
    {'Use Uiposition': {'use_uiposition': True}},
    {'Position Offset Relative': {'position_offset_relative': False}},
    {'Use Time Unfiltered Stereo Mapping Curve': {'use_time_unfiltered_stereo_mapping_curve': True}},
    {'Use Doppler': {'use_doppler': True}},
    {'Stop Match End': {'stop_match_end': 'true'}},
    {'Stop Loading': {'stop_loading': 'true'}},
    {'Join Non Mvp Group': {'join_non_mvp_group': 'true'}},
    {'Priority Override': {'priority_override': 'true'}},
    {'Loop Track': {'loop_track': 'true'}},
    {'Should Queue Track': {'should_queue_track': 'true'}},
    {'Update Track Syncpoint Index': {'update_track_syncpoint_index': 'true'}},
    {'Stop Start Round': {'stop_start_round': 'true'}},
    {'Stop Tensec Count': {'stop_tensec_count': 'true'}},
    {'Stop Bomb Planted': {'stop_bomb_planted': 'true'}},
    {'Stop Got Hostage': {'stop_got_hostage': 'true'}},
    {'Stop Music Except Mvp': {'stop_music_except_mvp': 'true'}},
    {'Skip If Muted': {'skip_if_muted': 'true'}},
    {'Test Mvp Block': {'test_mvp_block': 'true'}},
    {'Check For Classic Deathcam': {'check_for_classic_deathcam': 'true'}},
    {'Stop Won Mvp': {'stop_won_mvp': 'true'}},
    {'Block Won Lost': {'block_won_lost': 'true'}},
    {'Occlusion': {'occlusion': True}},

    # Combobox
    {'Dsp Preset': {'dsp_preset': 'reverb_9_mediumChamber'}},
    {'Soundevent 01': {'soundevent_01': ''}},
    {'Mixgroup': {'mixgroup': 'Amb_Common'}},
    {'Type': {'type': 'csgo_mega'}},
    {'Base': {'base': 'amb.base'}},
    {'Metadata': {'metadata': 'mediumfs 1000'}},
    {'Set Mixlayer Layer': {'set_mixlayer_layer': 'PlayerAttackerFeedbackLayer'}},
    {'Block Other Name': {'block_other_name': 'DeathHeadShotArmor'}},
    {'Volume Convar': {'volume_convar': 'snd_surf_volume_slide'}},
    {'Mixlayer Name': {'mixlayer_name': 'VideoClipMixLayer'}},

    # Curve
    {'Distance Volume Mapping Curve': {'distance_volume_mapping_curve': [[97.14286, 1.0, -0.001763, -0.001763, 2.0, 3.0], [2000.0, 0.0, -0.000526, -0.000526, 1.0, 1.0]]}},
    {'Fadetime Volume Mapping Curve': {'fadetime_volume_mapping_curve': [[0.0, 1.0, -1.223776, -1.223776, 2.0, 3.0], [0.691429, 0.0, 0.0, 0.0, 2.0, 3.0]]}},
    {'Distance Unfiltered Stereo Mapping Curve': {'distance_unfiltered_stereo_mapping_curve': [[0.0, 0.0, 0.0, 0.0, 2.0, 3.0], [300.0, 0.0, 0.0, 0.0, 2.0, 3.0]]}},
    {'Time Volume Mapping Curve': {'time_volume_mapping_curve': [[0.0, 0.0, 0.0, 0.0, 2.0, 3.0], [1.0, 1.0, 0.0, 0.0, 2.0, 3.0]]}},
    {'Impact Speed Input Volume Mapping Curve': {'impact_speed_input_volume_mapping_curve': [[6.857143, 0.0, 0.0, 0.0, 2.0, 3.0], [92.571426, 0.426471, 0.002544, 0.002544, 3.0, 1.0], [400.0, 1.0, 0.0, 0.0, 2.0, 3.0]]}},
    {'Time Mixlayer Amount Curve': {'time_mixlayer_amount_curve': [[0.0, 1.0, -0.045188, -0.045188, 2.0, 3.0], [0.137795, 1.0, -3.242553, -3.242553, 3.0, 1.0], [0.308399, 0.0, 0.0, 0.0, 2.0, 3.0]]}},
    {'Velocity Volume Curve': {'velocity_volume_curve': [[0.0, 0.0, 0.0, 0.0, 2.0, 3.0], [2300.0, 0.0, 0.0, 0.0, 2.0, 3.0], [2600.0, 1.0, 0.0, 0.0, 2.0, 3.0]]}},
    {'Time Unfiltered Stereo Mapping Curve': {'time_unfiltered_stereo_mapping_curve': [[0.0, 0.0, 0.0, 0.0, 2.0, 3.0], [0.542857, 0.0, 0.0, 0.0, 2.0, 3.0], [1.928571, 1.0, 0.0, 0.0, 2.0, 3.0]]}},
    {'Syncpoints 01': {'syncpoints_01': [0.0, 1.996, 3.989, 5.993, 7.992, 9.985, 12.002, 14.007, 15.982, 17.993, 19.98, 21.991, 23.99, 25.995, 27.999, 29.993, 32.003, 33.996, 36.001, 37.988, 39.999, 42.01, 43.991, 45.99, 47.989, 49.994, 51.999, 53.992]}},
    {'Syncpoints 02': {'syncpoints_02': [0.0, 2.002, 4.012, 6.035, 8.07, 10.085, 12.104, 14.122, 16.138, 18.152, 20.166, 22.188, 24.196, 26.214, 28.226, 30.235, 32.256, 34.27, 36.288, 38.306]}},
    {'Syncpoints 03': {'syncpoints_03': [3.075, 4.951, 4.798, 6.838, 8.72, 10.608, 12.485, 14.38, 16.269, 18.153, 20.036, 21.921, 23.81, 25.697, 27.576, 29.467, 31.349, 33.219, 35.115, 37.0, 38.882, 40.764, 42.652, 44.539, 46.421, 48.306, 50.191, 52.076, 53.978, 55.851]}},
]
dsp_preset_objects = [
    'reverb_2_crawlSpace',
    'reverb_3_smallTunnels',
    'reverb_4_smallCarpetRoom',
    'reverb_5_smallRoom',
    'reverb_6_largeRoom',
    'reverb_7_mediumHall',
    'reverb_8_mediumCarpetRoom',
    'reverb_9_mediumChamber',
    'reverb_10_warehouse',
    'reverb_11_smallBright9',
    'reverb_12_mediumBright',
    'reverb_13_largeBright',
    'reverb_14_brightHallway',
    'reverb_15_largeCarpetRoom',
    'reverb_16_carpetCorridor',
    'reverb_17_smallConcrete',
    'reverb_18_mediumConcrete',
    'reverb_19_largeConcrete',
    'reverb_20_outsideAlley',
    'reverb_21_outsideStreet',
    'reverb_22_outsideOpen',
    'reverb_23_smallBathroom',
    'reverb_24_largeBathroom'
]
type_objects = ['csgo_mega']
mixgroup_objects = ['ArmsRace', 'Weapons', 'UI', 'voip', 'World', 'Music', 'BuyMusic', 'DuckingMusic', 'SelectedMusic', 'All', 'Footsteps', 'Foley', 'Physics', 'BulletImpacts', 'Explosions', 'ExplosionsDistant', 'Ambient', 'WeaponsDistant', 'Exceptions', 'Amb_Common', 'Aztec', 'Assault', 'Baggage', 'Bank', 'Boathouse', 'Canals', 'Cbble', 'Chateau', 'Compound', 'Coop', 'Dust', 'Dust2', 'Havana', 'House', 'Inferno', 'Italy', 'Lunacy', 'Militia', 'Mill', 'Mirage', 'Monastery', 'Nuke', 'Office', 'Overpass', 'Piranesi', 'Port', 'Prodigy', 'Shacks', 'Shoots', 'Train', 'Training', 'Vertigo', 'PlayerDamage', 'KillCard', 'PlayerVictim', 'Anubis', 'VO']
soundevent_blank = {}