name: PR Check

on:
  pull_request:
    paths-ignore:
      - '*.md'
      - 'docs/**'
      - '.github/*_TEMPLATE/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    with:
      channel: dev
